<a href="https://colab.research.google.com/github/aymuos/endgame/blob/main/check_batch_dynamic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Batch Dynamics Check — Single City

This notebook loads a single city's delivery CSV, sorts by `delivery_user_id` and `receipt_time`, computes batch features (batch size, dispatch rank, batch id) and checks for `dynamic pickup` events: where a courier receives a new batch while some orders from the previous batch remain undelivered (sign_time > next_batch_receipt_time).

Edit `CITY` and `CITY_CSV_PATHS` below to point to your local files if needed.

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
# Imports and config
import os
import sys
from datetime import datetime
import numpy as np
import pandas as pd

# Select city to analyse (case-sensitive, e.g. 'Shanghai')
CITY = 'Shanghai'

# Candidate paths (edit if your files live elsewhere)
CITY_CSV_PATHS = [
    '/content/drive/MyDrive/ml/PROCESSED/matched/city_divided/shanghai_data.csv',
]

def find_existing_path(candidates):
    for p in candidates:
        if os.path.exists(p):
            return p
    return None

CITY_CSV = find_existing_path(CITY_CSV_PATHS)
if CITY_CSV is None:
    print('No candidate CSV found. Please update CITY_CSV_PATHS to point to your file.')
    sys.exit(1)

print('Using CSV:', CITY_CSV)

Using CSV: /content/drive/MyDrive/ml/PROCESSED/matched/city_divided/shanghai_data.csv

In [11]:
# Load the CSV with pandas (robust for various environments)
df = pd.read_csv(CITY_CSV)

# Ensure datetime columns parsed
for col in ['receipt_time', 'sign_time']:
    if col in df.columns and not np.issubdtype(df[col].dtype, np.datetime64):
        df[col] = pd.to_datetime(df[col], format='%Y-%m-%d %H:%M:%S', errors='coerce')

# Derive or ensure 'ds' (MMDD) exists. If receipt_time contains full datetime, use it;
# otherwise rely on an existing 'ds' column in the CSV.
if 'ds' not in df.columns:
    if 'receipt_time' in df.columns:
        df['ds'] = df['receipt_time'].dt.strftime('%m%d')
    else:
        df['ds'] = pd.NA
# Normalize ds to string (zero-padded MMDD)
df['ds'] = df['ds'].astype(str)

# Basic cleaning: drop rows missing key timestamps or courier id
df = df.dropna(subset=['receipt_time', 'delivery_user_id'])
df['delivery_user_id'] = df['delivery_user_id'].astype(str)

# Compute eta_mins if present/needed
if 'sign_time' in df.columns:
    df['eta_mins'] = (df['sign_time'] - df['receipt_time']).dt.total_seconds() / 60

# Sort as requested: by delivery_user_id then ds then receipt_time then order_id (if exists)
sort_cols = ['delivery_user_id', 'ds', 'receipt_time']
if 'order_id' in df.columns:
    sort_cols.append('order_id')
df = df.sort_values(sort_cols).reset_index(drop=True)

print('Loaded rows:', len(df))
df.head(3)

Loaded rows: 34735

,order_id,from_dipan_id,delivery_user_id,poi_lng,poi_lat,aoi_id,typecode,receipt_time,receipt_lng,receipt_lat,sign_time,sign_lng,sign_lat,ds,city,eta_mins
0,04fc2f9b94c6de1069d525e259ca7d82,2cf0d24cee3c0ad128ad76019f018f9a,00fca617ad52d2deb9650342901a1940,1.056095e+07,-7.454289e+06,8cd1cc14a0e53f305b80dbae07983ada,203ac3454d75e02ebb0a3c6f51d735e4,2021-03-18 07:24:00,1.056254e+07,-7.452504e+06,2021-03-18 08:29:00,NaN,NaN,318,Shanghai,65.0
1,0a11f8e3fee958aa3df8e7ceab8a5146,2cf0d24cee3c0ad128ad76019f018f9a,00fca617ad52d2deb9650342901a1940,1.056086e+07,-7.454063e+06,d4a631a1f2165ab095adb674382b3eea,203ac3454d75e02ebb0a3c6f51d735e4,2021-03-18 07:24:00,1.056254e+07,-7.452508e+06,2021-03-18 08:47:00,NaN,NaN,318,Shanghai,83.0
2,c1039a5e963e50ac59b037f9f0c7a3ac,2cf0d24cee3c0ad128ad76019f018f9a,00fca617ad52d2deb9650342901a1940,1.056094e+07,-7.454282e+06,8cd1cc14a0e53f305b80dbae07983ada,203ac3454d75e02ebb0a3c6f51d735e4,2021-03-18 07:24:00,1.056252e+07,-7.452511e+06,2021-03-18 08:09:00,NaN,NaN,318,Shanghai,45.0

In [14]:
# Compute batch features: batch_size, batch_id, batch_rank_dispatch
# Definition: orders sharing (delivery_user_id, ds, receipt_time) are a batch — include ds to separate days
group_cols = ['delivery_user_id', 'ds', 'receipt_time']
if 'order_id' in df.columns:
    df['batch_size'] = df.groupby(group_cols)['order_id'].transform('count')
else:
    df['batch_size'] = df.groupby(group_cols).transform('size')
# batch_id: courier__ds__epoch(receipt_time) — ds ensures uniqueness when receipt_time lacks a date
df['batch_id'] = df['delivery_user_id'] + '__' + df['ds'].astype(str) + '__' + df['receipt_time'].astype('int64').floordiv(10**9).astype(str)
# dispatch rank: deterministic order within the simultaneous push — use order_id if available else row order
if 'order_id' in df.columns:
    df['batch_rank_dispatch'] = df.groupby(group_cols)['order_id'].cumcount()
else:
    df['batch_rank_dispatch'] = df.groupby(group_cols).cumcount()

# actual rank by sign_time (post-hoc), stored only for diagnostics if sign_time exists
if 'sign_time' in df.columns:
    df['batch_rank_actual'] = df.groupby(group_cols)['sign_time'].rank(method='first').astype('Int64') - 1
else:
    df['batch_rank_actual'] = pd.NA

print('Batch features computed. Example:')
print(display(df[['delivery_user_id','ds','receipt_time','batch_id','batch_size','batch_rank_dispatch','batch_rank_actual']].head(8)))

Batch features computed. Example:

,delivery_user_id,ds,receipt_time,batch_id,batch_size,batch_rank_dispatch,batch_rank_actual
0,00fca617ad52d2deb9650342901a1940,318,2021-03-18 07:24:00,00fca617ad52d2deb9650342901a1940__318__1616052240,4,0,1
1,00fca617ad52d2deb9650342901a1940,318,2021-03-18 07:24:00,00fca617ad52d2deb9650342901a1940__318__1616052240,4,1,3
2,00fca617ad52d2deb9650342901a1940,318,2021-03-18 07:24:00,00fca617ad52d2deb9650342901a1940__318__1616052240,4,2,0
3,00fca617ad52d2deb9650342901a1940,318,2021-03-18 07:24:00,00fca617ad52d2deb9650342901a1940__318__1616052240,4,3,2
4,00fca617ad52d2deb9650342901a1940,318,2021-03-18 07:25:00,00fca617ad52d2deb9650342901a1940__318__1616052300,6,0,5
5,00fca617ad52d2deb9650342901a1940,318,2021-03-18 07:25:00,00fca617ad52d2deb9650342901a1940__318__1616052300,6,1,0
6,00fca617ad52d2deb9650342901a1940,318,2021-03-18 07:25:00,00fca617ad52d2deb9650342901a1940__318__1616052300,6,2,1
7,00fca617ad52d2deb9650342901a1940,318,2021-03-18 07:25:00,00fca617ad52d2deb9650342901a1940__318__1616052300,6,3,2

None

In [18]:
# Check for dynamic pickup per day: for each courier, for each batch, did a next batch arrive while some
# orders in the current batch were still undelivered? (i.e., sign_time > next_batch_receipt_time)

# We need sign_time for this diagnostic; if absent, report and stop
if 'sign_time' not in df.columns:
    print('sign_time column missing — cannot compute dynamic pickup. Add sign_time to CSV and retry.')
else:
    # Analyse per-day (ds) so that batches are isolated by day
    ds_values = sorted(df['ds'].dropna().unique())
    if len(ds_values) == 0:
        ds_values = [None]
    for ds_val in ds_values:
        print('\n=== Day:', ds_val, '===')
        if ds_val is None:
            df_day = df.copy()
        else:
            df_day = df[df['ds'] == ds_val].copy()
        if df_day.empty:
            print('No data for this day.')
            continue

        # Build per-courier batch summary sorted by receipt_time for this day
        if 'order_id' in df_day.columns:
            batches = df_day.groupby(['delivery_user_id','batch_id'], as_index=False).agg({
                'receipt_time': 'first',
                'batch_size': 'first',
                'order_id': lambda s: list(s),
            })
        else:
            batches = df_day.groupby(['delivery_user_id','batch_id'], as_index=False).agg({
                'receipt_time': 'first',
                'batch_size': 'first',
            })
        batches = batches.sort_values(['delivery_user_id','receipt_time']).reset_index(drop=True)

        # Map next receipt_time per courier (shift) within the same day
        batches['next_batch_receipt'] = batches.groupby('delivery_user_id')['receipt_time'].shift(-1)

        # For each batch, count unfinished orders at next_batch_receipt
        def count_unfinished(row):
            if pd.isna(row['next_batch_receipt']):
                return 0
            mask = (df_day['batch_id'] == row['batch_id']) & (df_day['sign_time'] > row['next_batch_receipt'])
            return int(mask.sum())

        batches['unfinished_at_next'] = batches.apply(count_unfinished, axis=1)
        batches['dynamic_pickup_flag'] = (batches['unfinished_at_next'] > 0).astype(int)

        # Summary statistics for this day
        total_batches = len(batches)
        dyn_count = int(batches['dynamic_pickup_flag'].sum())
        if total_batches > 0:
            print(f'Total batches (detected): {total_batches:,}')
            print(f'Batches with dynamic pickup (new batch arrived while previous had unfinished deliveries): {dyn_count:,} ({dyn_count/total_batches*100:.2f} %)')
        else:
            print('No batches detected for this day.')

        # Per-courier dynamic pickup analysis for this day
        print('\n--- Per-courier Dynamic Pickup for Day:', ds_val, '---')
        courier_summary = batches.groupby('delivery_user_id').agg(
            total_batches_courier=('batch_id', 'count'),
            dynamic_pickup_batches_courier=('dynamic_pickup_flag', 'sum')
        ).reset_index()
        courier_summary['pct_dynamic_pickup'] = (
            courier_summary['dynamic_pickup_batches_courier'] /
            courier_summary['total_batches_courier'] * 100
        )
        # Display top 10 couriers by percentage of dynamic pickups
        display(courier_summary[courier_summary['total_batches_courier'] > 0]
                .sort_values('pct_dynamic_pickup', ascending=False).head(10))
        if len(courier_summary) > 10:
            print(f'... and {len(courier_summary) - 10} more couriers (showing top 10 by percentage).')

        # Distribution by batch size
        if total_batches > 0:
            size_tab = batches.groupby('batch_size')['dynamic_pickup_flag'].agg(['count','sum']).reset_index()
            size_tab['pct_dynamic'] = size_tab['sum'] / size_tab['count'] * 100
            display(size_tab.sort_values('batch_size').head(20))

        # Show example cases where dynamic pickup happened
        examples = batches[batches['dynamic_pickup_flag'] == 1].head(10)
        if not examples.empty:
            for _, r in examples.iterrows():
                print('Example courier:', r['delivery_user_id'], 'receipt_time:', r['receipt_time'])
                display(df_day[df_day['batch_id'] == r['batch_id']][['order_id','receipt_time','sign_time','batch_rank_dispatch','batch_rank_actual']].sort_values('batch_rank_dispatch'))
        else:
            print('No dynamic pickup examples found for this day.')

        # Optional: save batch-level summary for this day
        OUT = './batch_dynamics_summary_' + CITY.lower() + '_' + str(ds_val) + '.csv'
        batches.to_csv(OUT, index=False)
        print('Saved batch summary to', OUT)

=== Day: 318 ===
Total batches (detected): 903
Batches with dynamic pickup (new batch arrived while previous had unfinished deliveries): 631 (69.88 %)

--- Per-courier Dynamic Pickup for Day: 318 ---

,delivery_user_id,total_batches_courier,dynamic_pickup_batches_courier,pct_dynamic_pickup
19,2cd6a9a317e3cc0dc8aae36443f5d806,16,14,87.500000
20,2eac82477425ea9e3b76985a3e8a1715,21,18,85.714286
2,0624b34f057ea763a1af4721b89d7b7c,7,6,85.714286
55,a953e787e74cc318462aa121e52d9896,21,18,85.714286
42,6caec65b164b4e29a27509a10c3736a6,6,5,83.333333
56,b2189fdf3fa9e164ac2200e0b0d80af4,12,10,83.333333
11,156ba74f4cbb5799f74ba615fa586104,17,14,82.352941
63,d1fda897c90233353f906db959a62b17,17,14,82.352941
40,6a76231746403d5448f6a5217034980d,16,13,81.250000
18,2bda9e538a98b75de75a2df2114c5f9b,16,13,81.250000

... and 69 more couriers (showing top 10 by percentage).

    batch_size  count  sum  pct_dynamic
0            1    377  248    65.782493
1            2    216  159    73.611111
2            3    137  102    74.452555
3            4     72   53    73.611111
4            5     42   29    69.047619
5            6     27   15    55.555556
6            7     16   14    87.500000
7            8      9    5    55.555556
8            9      5    4    80.000000
9           11      1    1   100.000000
10          14      1    1   100.000000

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-18 07:24:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
0,04fc2f9b94c6de1069d525e259ca7d82,2021-03-18 07:24:00,2021-03-18 08:29:00,0,1
1,0a11f8e3fee958aa3df8e7ceab8a5146,2021-03-18 07:24:00,2021-03-18 08:47:00,1,3
2,c1039a5e963e50ac59b037f9f0c7a3ac,2021-03-18 07:24:00,2021-03-18 08:09:00,2,0
3,ee38d0d35f6f58fa4271ec8f408835c1,2021-03-18 07:24:00,2021-03-18 08:38:00,3,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-18 07:25:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
4,2394eabf048d491cc8011944d125a623,2021-03-18 07:25:00,2021-03-18 09:57:00,0,5
5,52b897a05494c7e2f340f170e6e838cd,2021-03-18 07:25:00,2021-03-18 09:03:00,1,0
6,76fb4eaadc4bf1603e8ec3ce9298873c,2021-03-18 07:25:00,2021-03-18 09:08:00,2,1
7,bb4fe8862aa8e0b0914c0ad09006d520,2021-03-18 07:25:00,2021-03-18 09:18:00,3,2
8,f0709cc90dfcf23ad54ebb4f4adb80c5,2021-03-18 07:25:00,2021-03-18 09:28:00,4,3
9,f5c702a2f154eb3392137d3a2987e993,2021-03-18 07:25:00,2021-03-18 09:49:00,5,4

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-18 11:36:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
12,09b6d72a3a7aa5c53cabefbf77717900,2021-03-18 11:36:00,2021-03-18 14:51:00,0,4
13,46e1b585c0f1ede5f990eda320142ec1,2021-03-18 11:36:00,2021-03-18 14:44:00,1,3
14,59dfc4e58601225fc4536fed6b1df6b5,2021-03-18 11:36:00,2021-03-18 13:35:00,2,0
15,d27edfef971ceea57d0804fe5e5b7bed,2021-03-18 11:36:00,2021-03-18 14:05:00,3,1
16,d91913d1697b76c26859cf626dda77c4,2021-03-18 11:36:00,2021-03-18 14:20:00,4,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-18 11:37:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
17,0e46558bd46e84136ba77a2d3a5f070c,2021-03-18 11:37:00,2021-03-18 12:36:00,0,0
18,4535bd5c8439bea6d5a5526cab870b92,2021-03-18 11:37:00,2021-03-18 14:11:00,1,4
19,723314bfba049858d8f278ec764f575e,2021-03-18 11:37:00,2021-03-18 14:56:00,2,7
20,7dd01878f69081a861cccc3da63e302c,2021-03-18 11:37:00,2021-03-18 15:04:00,3,8
21,8dd396890a3a23526b1e6944779203bc,2021-03-18 11:37:00,2021-03-18 12:48:00,4,1
22,8f9efd3fe09acf9567305e2fb15cd378,2021-03-18 11:37:00,2021-03-18 14:28:00,5,5
23,95a71cde3868446760bd3171cdabab7f,2021-03-18 11:37:00,2021-03-18 13:43:00,6,3
24,ab0ea8c3ef89391102e1fca42780d64d,2021-03-18 11:37:00,2021-03-18 13:28:00,7,2
25,f248b3b86f683d2f395bc42dff4e3c20,2021-03-18 11:37:00,2021-03-18 14:36:00,8,6

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-18 16:38:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
27,346cb80c0bdcda0079e61169d618e913,2021-03-18 16:38:00,2021-03-18 18:36:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-18 16:39:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
28,b635863292ab0078e0aa36f28f19e3ff,2021-03-18 16:39:00,2021-03-18 17:48:00,0,0
29,b8a747504d37712c3f88aa025701d243,2021-03-18 16:39:00,2021-03-18 19:06:00,1,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-18 16:40:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
30,458e7916b08ae87e33dd12dde6811202,2021-03-18 16:40:00,2021-03-18 18:28:00,0,4
31,8f523caf9988911d649a731d3494ba9b,2021-03-18 16:40:00,2021-03-18 18:00:00,1,2
32,8ff8235713633bc861aa8480a11b08a9,2021-03-18 16:40:00,2021-03-18 17:54:00,2,1
33,918a48f9e935720863d50197b1f5d11b,2021-03-18 16:40:00,2021-03-18 17:31:00,3,0
34,c1402124bb10897eb3e330097b3b0a48,2021-03-18 16:40:00,2021-03-18 18:13:00,4,3

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-18 16:41:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
35,056f054bb74d527b64712b7de474ee52,2021-03-18 16:41:00,2021-03-18 18:20:00,0,0
36,2050687c3abf61b1755b765700d42583,2021-03-18 16:41:00,2021-03-18 18:52:00,1,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-18 16:46:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
37,aa9800aa73682b2c8f05163750d75f10,2021-03-18 16:46:00,2021-03-18 18:07:00,0,0

Example courier: 02aa270595a0d24b1c9d2636fe249ebc receipt_time: 2021-03-18 10:43:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
551,56eb737fcc4107ce3d0e8713f56fa196,2021-03-18 10:43:00,2021-03-18 12:14:00,0,0
552,e1647c1a8e55a1312178b67cd5d633d1,2021-03-18 10:43:00,2021-03-18 20:59:00,1,1

Saved batch summary to ./batch_dynamics_summary_shanghai_318.csv

=== Day: 319 ===
Total batches (detected): 909
Batches with dynamic pickup (new batch arrived while previous had unfinished deliveries): 628 (69.09 %)

--- Per-courier Dynamic Pickup for Day: 319 ---

,delivery_user_id,total_batches_courier,dynamic_pickup_batches_courier,pct_dynamic_pickup
1,02aa270595a0d24b1c9d2636fe249ebc,7,6,85.714286
9,156ba74f4cbb5799f74ba615fa586104,14,12,85.714286
19,2eac82477425ea9e3b76985a3e8a1715,18,15,83.333333
54,a953e787e74cc318462aa121e52d9896,18,15,83.333333
67,dbf1999be46b5dd2c1e475c3ca8d2de2,18,15,83.333333
26,3d402c6f05639a1998cc32bbd40d3291,29,24,82.758621
35,64f4e76e5f04dfbd0ffcf6b803a9f4f8,17,14,82.352941
34,64c188995bbf44eb00e3d988bfdc7a7a,16,13,81.250000
37,6a76231746403d5448f6a5217034980d,16,13,81.250000
48,956fa147a5956d928b8c9734a98828cf,21,17,80.952381

... and 69 more couriers (showing top 10 by percentage).

    batch_size  count  sum  pct_dynamic
0            1    367  222    60.490463
1            2    200  155    77.500000
2            3    133   95    71.428571
3            4     89   75    84.269663
4            5     55   43    78.181818
5            6     27   20    74.074074
6            7     14    6    42.857143
7            8      8    3    37.500000
8            9      8    6    75.000000
9           10      3    1    33.333333
10          11      1    1   100.000000
11          12      2    0     0.000000
12          13      1    0     0.000000
13          14      1    1   100.000000

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-19 07:31:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
39,2c594368fcbd22124079999fa21ad026,2021-03-19 07:31:00,2021-03-19 08:08:00,0,0
40,7a44952f78ca6a4565f7a02ed9997e04,2021-03-19 07:31:00,2021-03-19 08:28:00,1,2
41,d21a023dfadc8d17b3d27dde85e5d9f6,2021-03-19 07:31:00,2021-03-19 08:15:00,2,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-19 07:32:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
42,adcaad77afdcc5a5ffe9a803b7eb3b07,2021-03-19 07:32:00,2021-03-19 08:34:00,0,1
43,f78027ae9d59bc50a232c095b72fa1ed,2021-03-19 07:32:00,2021-03-19 08:40:00,1,2
44,f7ec3bd25381d2e00ac4c48d6c8df94d,2021-03-19 07:32:00,2021-03-19 08:21:00,2,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-19 07:34:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
45,8f3b2cc241e1d5d6da081a2bed767541,2021-03-19 07:34:00,2021-03-19 08:56:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-19 09:27:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
47,54e2d198a530a04cd851bf9a956cf7a9,2021-03-19 09:27:00,2021-03-19 10:46:00,0,2
48,6e0820c58d70fa7aefba38440cc63731,2021-03-19 09:27:00,2021-03-19 10:13:00,1,1
49,ad973b4c78b3b1e1a3c90942b0f8f775,2021-03-19 09:27:00,2021-03-19 09:57:00,2,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-19 09:28:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
50,462f1dbb57b71d1cf8b5aa982a88e7f6,2021-03-19 09:28:00,2021-03-19 11:33:00,0,2
51,51c6ec3c3ce3c1d1343275c921a54281,2021-03-19 09:28:00,2021-03-19 10:40:00,1,0
52,791ef9a32017bbb244e842341e23c4dc,2021-03-19 09:28:00,2021-03-19 11:39:00,2,3
53,a864eed969922d6a93e4b0622fb0e43d,2021-03-19 09:28:00,2021-03-19 11:49:00,3,4
54,e449aed92632492b5ec88c8ed4982c5e,2021-03-19 09:28:00,2021-03-19 11:19:00,4,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-19 12:36:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
56,5bba96ccb62475615cf1b14eb5c60845,2021-03-19 12:36:00,2021-03-19 13:57:00,0,1
57,c09355ce75bb05c9b11804245d91445b,2021-03-19 12:36:00,2021-03-19 13:40:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-19 12:37:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
58,27c4b059ec3f07752a7a5f25ea848931,2021-03-19 12:37:00,2021-03-19 13:18:00,0,0
59,61e214ee19814edf309e3736f89e92bd,2021-03-19 12:37:00,2021-03-19 13:24:00,1,1
60,d0191d13e8c587b7e99436ebb33a5979,2021-03-19 12:37:00,2021-03-19 14:17:00,2,3
61,d5e4775933d7d2494d8eda85f30fd885,2021-03-19 12:37:00,2021-03-19 13:31:00,3,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-19 12:38:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
62,2a11c3e46b4831f5a231326011391165,2021-03-19 12:38:00,2021-03-19 13:51:00,0,0
63,a2310ee64391efef9b4495b31ca998a4,2021-03-19 12:38:00,2021-03-19 14:47:00,1,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-19 16:45:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
66,9768931e4f718f3b8dbe2c98a4bd14a4,2021-03-19 16:45:00,2021-03-19 18:37:00,0,1
67,b175d390a11fd8321ac6d27bb61272ed,2021-03-19 16:45:00,2021-03-19 18:08:00,1,0

Example courier: 02aa270595a0d24b1c9d2636fe249ebc receipt_time: 2021-03-19 10:51:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
573,c913c7c5362d2b488e55f1c9b71c695e,2021-03-19 10:51:00,2021-03-21 18:33:00,0,0

Saved batch summary to ./batch_dynamics_summary_shanghai_319.csv

=== Day: 320 ===
Total batches (detected): 914
Batches with dynamic pickup (new batch arrived while previous had unfinished deliveries): 636 (69.58 %)

--- Per-courier Dynamic Pickup for Day: 320 ---

,delivery_user_id,total_batches_courier,dynamic_pickup_batches_courier,pct_dynamic_pickup
9,156ba74f4cbb5799f74ba615fa586104,22,21,95.454545
23,3d402c6f05639a1998cc32bbd40d3291,15,14,93.333333
18,2eac82477425ea9e3b76985a3e8a1715,27,24,88.888889
55,b2189fdf3fa9e164ac2200e0b0d80af4,8,7,87.500000
50,99aa0748abd2f8511f3271187eccf820,14,12,85.714286
52,a2b97a310a6ac35c4480b26684f29aa7,14,12,85.714286
39,6a76231746403d5448f6a5217034980d,20,17,85.000000
80,faa55abcf03dce5c565a139c2c31e84f,19,16,84.210526
32,58e622d6f803e740cc2f96d31f08ed1f,19,16,84.210526
41,6caec65b164b4e29a27509a10c3736a6,6,5,83.333333

... and 74 more couriers (showing top 10 by percentage).

    batch_size  count  sum  pct_dynamic
0            1    354  208    58.757062
1            2    226  183    80.973451
2            3    137  106    77.372263
3            4     87   62    71.264368
4            5     48   38    79.166667
5            6     24   16    66.666667
6            7     17    8    47.058824
7            8      8    5    62.500000
8            9      2    2   100.000000
9           10      5    2    40.000000
10          11      5    5   100.000000
11          15      1    1   100.000000

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-20 07:23:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
76,0cf0b9af354cc5fb07b1fcaa6012bb43,2021-03-20 07:23:00,2021-03-20 08:37:00,0,2
77,0ecea9c6e5c3a031d59ff8fb39862f01,2021-03-20 07:23:00,2021-03-20 08:18:00,1,0
78,7035fa375117436fef2e569c9efe7324,2021-03-20 07:23:00,2021-03-20 08:42:00,2,3
79,8f6993b2240798c6a3be018d112f0de1,2021-03-20 07:23:00,2021-03-20 08:26:00,3,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-20 07:24:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
80,149585bdd71d0b661e9f6ee81d51e862,2021-03-20 07:24:00,2021-03-20 08:54:00,0,3
81,58a282be9c8c680e90e3e55a1932fc3a,2021-03-20 07:24:00,2021-03-20 09:00:00,1,4
82,7033bc8f865aa06ca9425efeb9bcae2c,2021-03-20 07:24:00,2021-03-20 08:32:00,2,1
83,959b8c746b1d5367e854fec0fab518ac,2021-03-20 07:24:00,2021-03-20 09:34:00,3,5
84,a8c1908aa367087c596304e464eac400,2021-03-20 07:24:00,2021-03-20 08:11:00,4,0
85,e562201bb487ee2937e79b00315a58e7,2021-03-20 07:24:00,2021-03-20 08:47:00,5,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-20 12:51:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
88,2a0e2b34a1d63ac5379b6e1a789e0e6e,2021-03-20 12:51:00,2021-03-20 14:31:00,0,1
89,2e7b82eac6f1e59965ca0c5713e923d9,2021-03-20 12:51:00,2021-03-20 15:40:00,1,4
90,4fcfff6c6695301d77394783d3831cfe,2021-03-20 12:51:00,2021-03-20 14:25:00,2,0
91,57cdb82b0067690a8797c901d912c894,2021-03-20 12:51:00,2021-03-20 15:26:00,3,3
92,e9dc06b1ca19810ddbc8893d8579f6ab,2021-03-20 12:51:00,2021-03-20 14:49:00,4,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-20 17:01:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
98,53983f3536da63f5eaeb0594c71b71f7,2021-03-20 17:01:00,2021-03-20 19:15:00,0,1
99,9e0f5a34521f2e6afec031ec5fea2dab,2021-03-20 17:01:00,2021-03-20 19:29:00,1,2
100,dc612c8d48fc0ca0326b525656ddca39,2021-03-20 17:01:00,2021-03-20 18:27:00,2,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-20 17:02:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
101,540d9046f6053c41fb5affab5b5df619,2021-03-20 17:02:00,2021-03-20 17:57:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-20 17:03:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
102,12459bfa5b7d4a79f8eeeaf82ef6bed3,2021-03-20 17:03:00,2021-03-20 17:43:00,0,0
103,57f3ac15417ab3581c3c134d2c7fd86c,2021-03-20 17:03:00,2021-03-20 18:45:00,1,2
104,a7abd1bbbb484bd47f1eeda5df428d76,2021-03-20 17:03:00,2021-03-20 19:35:00,2,3
105,ccd80e0e1e8f74b4050a56f951510468,2021-03-20 17:03:00,2021-03-20 17:51:00,3,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-20 17:04:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
106,65f2389742ed34936a4611e957df2d04,2021-03-20 17:04:00,2021-03-20 18:11:00,0,1
107,6667d62c191822064b1c4b822e3b7145,2021-03-20 17:04:00,2021-03-20 18:33:00,1,3
108,770a0887b4f92dd211a9e797342380a9,2021-03-20 17:04:00,2021-03-20 18:03:00,2,0
109,909cdb504acf58d4a66faf6f19795c45,2021-03-20 17:04:00,2021-03-20 18:19:00,3,2
110,9307a935ab0d6f97bf05ae82633a1d06,2021-03-20 17:04:00,2021-03-20 18:51:00,4,4

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-20 17:05:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
111,af41709ba19baaf8d20d381cb75f9c55,2021-03-20 17:05:00,2021-03-20 19:24:00,0,0

Example courier: 02aa270595a0d24b1c9d2636fe249ebc receipt_time: 2021-03-20 10:45:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
585,cd27e9a005d150631709da10501f918b,2021-03-20 10:45:00,2021-03-23 12:55:00,0,0

Example courier: 02aa270595a0d24b1c9d2636fe249ebc receipt_time: 2021-03-20 10:46:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
586,5494f65778fdc65859a4744a9a66bd1c,2021-03-20 10:46:00,2021-03-20 19:55:00,0,1
587,d8c1ac8e6b07fcf858b07342ff7d5146,2021-03-20 10:46:00,2021-03-20 18:37:00,1,0

Saved batch summary to ./batch_dynamics_summary_shanghai_320.csv

=== Day: 321 ===
Total batches (detected): 978
Batches with dynamic pickup (new batch arrived while previous had unfinished deliveries): 652 (66.67 %)

--- Per-courier Dynamic Pickup for Day: 321 ---

,delivery_user_id,total_batches_courier,dynamic_pickup_batches_courier,pct_dynamic_pickup
12,156ba74f4cbb5799f74ba615fa586104,17,16,94.117647
66,ba13756ec3ac802658cf457f9bd12fde,19,16,84.210526
64,b2189fdf3fa9e164ac2200e0b0d80af4,6,5,83.333333
70,c399fd1cde8be68db155071945da5526,24,20,83.333333
20,2eac82477425ea9e3b76985a3e8a1715,18,15,83.333333
93,fef2195c3e5ac70ba8be0b007be46070,11,9,81.818182
80,dafa5f217fe7f20dcb725a6af1339876,16,13,81.250000
83,dd648d4143daa61906cdb8c283aedb56,16,13,81.250000
77,d3d20b5c70e919cad04f0484aade30cb,16,13,81.250000
44,6a76231746403d5448f6a5217034980d,16,13,81.250000

... and 84 more couriers (showing top 10 by percentage).

    batch_size  count  sum  pct_dynamic
0            1    354  200    56.497175
1            2    224  159    70.982143
2            3    152  117    76.973684
3            4    109   77    70.642202
4            5     62   43    69.354839
5            6     33   22    66.666667
6            7     22   18    81.818182
7            8      9    6    66.666667
8            9      4    3    75.000000
9           10      3    3   100.000000
10          11      1    1   100.000000
11          12      2    1    50.000000
12          13      2    1    50.000000
13          15      1    1   100.000000

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-21 07:24:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
113,94cb8486496bea4cd6246a3887bd77f0,2021-03-21 07:24:00,2021-03-21 09:18:00,0,4
114,b0162cbd1a4a5e3d99bbff1e64e0e7bc,2021-03-21 07:24:00,2021-03-21 09:02:00,1,2
115,dfc7faa0ff0ad02cdaa1b91f15fe863e,2021-03-21 07:24:00,2021-03-21 08:47:00,2,0
116,ed79a16c5d86dcc7d7a55a6ca0be2710,2021-03-21 07:24:00,2021-03-21 08:52:00,3,1
117,f144b2a9e1711d3d92e7dabe176de291,2021-03-21 07:24:00,2021-03-21 09:12:00,4,3

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-21 07:25:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
118,0809a68b499f45264391704c5c9ad2a4,2021-03-21 07:25:00,2021-03-21 08:37:00,0,0
119,19438369aaaaca5d9b657fbf216cc4bc,2021-03-21 07:25:00,2021-03-21 09:27:00,1,1
120,7c97dc5a911b1b04a319aa1881b168f3,2021-03-21 07:25:00,2021-03-21 09:33:00,2,2
121,f8c98874d71fe252063bd51289a9f622,2021-03-21 07:25:00,2021-03-21 09:39:00,3,3

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-21 07:26:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
122,363a7fa3b1c918aa90a959afda936827,2021-03-21 07:26:00,2021-03-21 09:52:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-21 12:45:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
127,9161fbedfc132b6bb50991f6155c63c4,2021-03-21 12:45:00,2021-03-21 14:40:00,0,1
128,fdb2867c8fb5ce01319ebfceadbb7187,2021-03-21 12:45:00,2021-03-21 13:46:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-21 12:46:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
129,73598fcc97bbdfa863fdc17760540e25,2021-03-21 12:46:00,2021-03-21 19:02:00,0,3
130,962e1770a89a19e984f8d0b25bb487cf,2021-03-21 12:46:00,2021-03-21 13:52:00,1,0
131,dc26972d66975b9316e4d91a3ec80ebf,2021-03-21 12:46:00,2021-03-21 14:47:00,2,2
132,ffb0b6d4c5b862a13ca155693f16de51,2021-03-21 12:46:00,2021-03-21 14:21:00,3,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-21 12:47:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
133,179338f4a836b285af069b1a3d10ea0e,2021-03-21 12:47:00,2021-03-21 13:39:00,0,1
134,5007b4ebe1897135af3bbd8e14f70b0b,2021-03-21 12:47:00,2021-03-21 14:10:00,1,2
135,73cc0e918003f25a64837ceb807f6cc1,2021-03-21 12:47:00,2021-03-21 14:15:00,2,3
136,f35714b40a4feef235bb06fd8cf78792,2021-03-21 12:47:00,2021-03-21 13:33:00,3,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-21 16:43:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
139,27f88e418a93266d74741a17b567cfde,2021-03-21 16:43:00,2021-03-21 17:07:00,0,0
140,357ad62ca349925db99d90c58296d182,2021-03-21 16:43:00,2021-03-21 18:27:00,1,3
141,47e8243a7f2925714c802c89f1a87382,2021-03-21 16:43:00,2021-03-21 17:15:00,2,1
142,629fe2570095b9682d1b5f25ae27f9a2,2021-03-21 16:43:00,2021-03-21 17:49:00,3,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-21 16:44:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
143,017d54f3bbb8307e34a2635bb62517ab,2021-03-21 16:44:00,2021-03-21 17:20:00,0,0
144,66f51545e9da4518903f36c38b8d2fa0,2021-03-21 16:44:00,2021-03-21 17:37:00,1,2
145,dc2b4263570f124d660e8ac618e257f1,2021-03-21 16:44:00,2021-03-21 17:29:00,2,1

Example courier: 02aa270595a0d24b1c9d2636fe249ebc receipt_time: 2021-03-21 10:43:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
603,63d2e2fb0807082da4d53bd1c579983f,2021-03-21 10:43:00,2021-03-21 17:22:00,0,0
604,a97013e0719f341258538983733cacb5,2021-03-21 10:43:00,2021-03-22 08:56:00,1,1

Example courier: 02aa270595a0d24b1c9d2636fe249ebc receipt_time: 2021-03-21 10:44:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
605,0e04b072d555c5ebe7059b25906fa089,2021-03-21 10:44:00,2021-03-21 17:40:00,0,0
606,177383c7c165bcc1520304d369873152,2021-03-21 10:44:00,2021-03-21 20:16:00,1,4
607,47ba3fb9069fa81c08bdab77ac14630b,2021-03-21 10:44:00,2021-03-21 19:53:00,2,3
608,9fa2a1e6c9f4ed69db26afd3ef48a8bd,2021-03-21 10:44:00,2021-03-21 19:46:00,3,2
609,b2700f15fd761d25172fcee51959f15a,2021-03-21 10:44:00,2021-03-21 19:24:00,4,1
610,d9109d6db2881bf2d4397c0e8d985207,2021-03-21 10:44:00,2021-03-21 20:40:00,5,5

Saved batch summary to ./batch_dynamics_summary_shanghai_321.csv

=== Day: 322 ===
Total batches (detected): 959
Batches with dynamic pickup (new batch arrived while previous had unfinished deliveries): 646 (67.36 %)

--- Per-courier Dynamic Pickup for Day: 322 ---

,delivery_user_id,total_batches_courier,dynamic_pickup_batches_courier,pct_dynamic_pickup
11,156ba74f4cbb5799f74ba615fa586104,14,13,92.857143
65,ba13756ec3ac802658cf457f9bd12fde,9,8,88.888889
32,50cae56dcd1b73f4b4e5fdf3188c7fb2,8,7,87.500000
19,2eac82477425ea9e3b76985a3e8a1715,23,20,86.956522
61,a953e787e74cc318462aa121e52d9896,23,20,86.956522
29,4ae813f01c224684851f3e7410ddb34e,7,6,85.714286
6,0b43ad0eea29bfd8e156f60e0f6b066e,20,17,85.000000
78,dafa5f217fe7f20dcb725a6af1339876,26,22,84.615385
8,0d6bd47d1eea4b6e553ba4fc18b332c7,19,16,84.210526
31,4f0ad958a57c88a3e29b991ea71c1d53,6,5,83.333333

... and 82 more couriers (showing top 10 by percentage).

    batch_size  count  sum  pct_dynamic
0            1    387  217    56.072351
1            2    189  147    77.777778
2            3    165  124    75.151515
3            4     81   62    76.543210
4            5     65   51    78.461538
5            6     27   14    51.851852
6            7     16   11    68.750000
7            8     13    7    53.846154
8            9      7    6    85.714286
9           10      4    3    75.000000
10          11      3    3   100.000000
11          12      1    0     0.000000
12          13      1    1   100.000000

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-22 07:23:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
150,0ff8259d58e10a39658b397734d51959,2021-03-22 07:23:00,2021-03-22 09:27:00,0,2
151,3fe0093e23241d6372b02983179c8c13,2021-03-22 07:23:00,2021-03-22 08:49:00,1,1
152,9d165362ef2c6649ec672d59198db517,2021-03-22 07:23:00,2021-03-22 08:23:00,2,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-22 07:24:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
153,4cbf159579d41ce37b4ab0e7c01f62bc,2021-03-22 07:24:00,2021-03-22 09:10:00,0,3
154,879d31c5aa2f6ffb6f5e1240a665dde5,2021-03-22 07:24:00,2021-03-22 09:04:00,1,2
155,bf89f7ed071504b49028a987d7f9e19a,2021-03-22 07:24:00,2021-03-22 08:15:00,2,0
156,dc696f312e0bd742e7f4873929abf6bf,2021-03-22 07:24:00,2021-03-22 09:19:00,3,4
157,de5bdf7a314ae9bbdb1c5f1060ec15a9,2021-03-22 07:24:00,2021-03-22 08:58:00,4,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-22 09:46:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
161,47b834989bfa25b3b4c39c30fef5a6d3,2021-03-22 09:46:00,2021-03-22 11:32:00,0,2
162,dd0208e7ace88f0a17280aad067fd5f6,2021-03-22 09:46:00,2021-03-22 11:26:00,1,1
163,e702e0f575f70477c70b4c775d67b011,2021-03-22 09:46:00,2021-03-22 11:16:00,2,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-22 12:15:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
167,1414f1aebdeddb492ab8cedb8f4b8053,2021-03-22 12:15:00,2021-03-22 13:43:00,0,1
168,5097c32343b373b3a0214015ae6cbb54,2021-03-22 12:15:00,2021-03-22 13:28:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-22 12:16:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
169,1b2c9b81278904d10ab385f10cadfbd0,2021-03-22 12:16:00,2021-03-22 13:58:00,0,1
170,6236bc3eb1a4c78b88b24703bc790131,2021-03-22 12:16:00,2021-03-22 13:11:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-22 12:17:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
171,2d105316a0adfe78539b6d4d5362c1e8,2021-03-22 12:17:00,2021-03-22 13:16:00,0,0
172,6d660b27969268bf896183c1b6ab6a16,2021-03-22 12:17:00,2021-03-22 14:17:00,1,2
173,a25fe8779564a24ce93272849bd2a784,2021-03-22 12:17:00,2021-03-22 13:34:00,2,1
174,a449860367554b4e18f8b153d034be4c,2021-03-22 12:17:00,2021-03-22 14:22:00,3,3

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-22 12:18:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
175,036db91273da95c6b35c12859f692395,2021-03-22 12:18:00,2021-03-22 12:48:00,0,1
176,0ad8cca907a69c2f11e2000bb7a7dc13,2021-03-22 12:18:00,2021-03-22 12:43:00,1,0
177,705bdde2be1be7880dcdd85419ab275c,2021-03-22 12:18:00,2021-03-22 12:54:00,2,2
178,f72ff1171e405a17c33812d19e249c94,2021-03-22 12:18:00,2021-03-22 13:52:00,3,3

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-22 16:32:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
180,2467afcaa534df4efa3a219e575a7e28,2021-03-22 16:32:00,2021-03-22 17:54:00,0,0

Example courier: 02aa270595a0d24b1c9d2636fe249ebc receipt_time: 2021-03-22 10:30:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
618,ad1d612141ee42190131fbac0838dcc4,2021-03-22 10:30:00,2021-03-22 18:01:00,0,0

Example courier: 02aa270595a0d24b1c9d2636fe249ebc receipt_time: 2021-03-22 10:31:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
619,96d67692b1923ee7eed30d6f43835ac5,2021-03-22 10:31:00,2021-03-23 19:46:00,0,0

Saved batch summary to ./batch_dynamics_summary_shanghai_322.csv

=== Day: 323 ===
Total batches (detected): 929
Batches with dynamic pickup (new batch arrived while previous had unfinished deliveries): 633 (68.14 %)

--- Per-courier Dynamic Pickup for Day: 323 ---

,delivery_user_id,total_batches_courier,dynamic_pickup_batches_courier,pct_dynamic_pickup
13,2455776169c7cd6fabf097a9b8d13756,8,7,87.500000
64,ba13756ec3ac802658cf457f9bd12fde,22,19,86.363636
1,02aa270595a0d24b1c9d2636fe249ebc,7,6,85.714286
53,9186a9f2138d421b852c1ad0abcc736b,20,17,85.000000
22,300db56eddc929594af6d741d231e0d3,20,17,85.000000
16,2bda9e538a98b75de75a2df2114c5f9b,13,11,84.615385
78,dbf1999be46b5dd2c1e475c3ca8d2de2,18,15,83.333333
44,6f0511943175b15a6f75d27c162c3982,12,10,83.333333
8,0d96b02a9ff59cef57bfad6df87161eb,23,19,82.608696
61,a953e787e74cc318462aa121e52d9896,17,14,82.352941

... and 79 more couriers (showing top 10 by percentage).

    batch_size  count  sum  pct_dynamic
0            1    359  222    61.838440
1            2    204  145    71.078431
2            3    149  112    75.167785
3            4     91   65    71.428571
4            5     49   36    73.469388
5            6     29   19    65.517241
6            7     21   17    80.952381
7            8      8    7    87.500000
8            9      8    4    50.000000
9           10      5    3    60.000000
10          11      1    1   100.000000
11          12      1    0     0.000000
12          13      1    0     0.000000
13          14      2    1    50.000000
14          15      1    1   100.000000

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-23 07:32:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
188,73a5b7fdb8d8d30875f815dca4de5e4c,2021-03-23 07:32:00,2021-03-23 08:53:00,0,2
189,ba476fd73af9360b2da8796ae4583efd,2021-03-23 07:32:00,2021-03-23 08:19:00,1,0
190,c7cb9f7bad15344f2b7962df95f2dd34,2021-03-23 07:32:00,2021-03-23 08:40:00,2,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-23 07:33:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
191,0f75581a52a5ca3ebab20f614c37ad7c,2021-03-23 07:33:00,2021-03-23 08:47:00,0,2
192,373cb6e0d323aa9a01fa9bb283d6c2ff,2021-03-23 07:33:00,2021-03-23 09:00:00,1,3
193,56b4d526a29f5eb85328d2b3973743b1,2021-03-23 07:33:00,2021-03-23 08:27:00,2,0
194,b1031b2be825511d694ff87689c394ab,2021-03-23 07:33:00,2021-03-23 08:32:00,3,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-23 07:34:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
195,81b4d7a70900098055c24a890e092d43,2021-03-23 07:34:00,2021-03-23 09:19:00,0,1
196,b0a5ef50c33d837837a62de1a3b514a5,2021-03-23 07:34:00,2021-03-23 09:11:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-23 07:35:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
197,07a633ed7bf5a974e036026a91149b26,2021-03-23 07:35:00,2021-03-23 10:02:00,0,1
198,b19d5e8966d5ddf5be7966c8b968cefd,2021-03-23 07:35:00,2021-03-23 09:55:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-23 10:23:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
201,1f6844dfb9a75e0b783f4f3f6301e0f8,2021-03-23 10:23:00,2021-03-23 11:48:00,0,1
202,2f166e651db7d8411108420ee21f6cbb,2021-03-23 10:23:00,2021-03-23 11:39:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-23 10:24:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
203,4120ba29ee9de9b64a2725a699223e43,2021-03-23 10:24:00,2021-03-23 11:53:00,0,2
204,77307b10181d1905bfa4a90aee51ffb1,2021-03-23 10:24:00,2021-03-23 11:19:00,1,1
205,827554eea23c2625c69bd7ceb021f5da,2021-03-23 10:24:00,2021-03-23 11:00:00,2,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-23 13:15:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
208,1591b718c458e36c633821ea92b016a8,2021-03-23 13:15:00,2021-03-23 15:23:00,0,1
209,a410e2b3b0dc104caef93117790ae216,2021-03-23 13:15:00,2021-03-23 14:17:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-23 13:16:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
210,1ffa48832c3066f03c027fd546bc8d13,2021-03-23 13:16:00,2021-03-23 15:13:00,0,1
211,57da4273aa024e68db0dbd172405d86f,2021-03-23 13:16:00,2021-03-23 15:36:00,1,2
212,df5d9828d9b7b173daa2166331ceac86,2021-03-23 13:16:00,2021-03-23 14:10:00,2,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-23 13:17:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
213,346eab5eea58370c3c1ceac032fbc1f8,2021-03-23 13:17:00,2021-03-23 15:05:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-23 13:19:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
214,c32f405235b196042e673a4fb8b893e2,2021-03-23 13:19:00,2021-03-23 14:55:00,0,0

Saved batch summary to ./batch_dynamics_summary_shanghai_323.csv

=== Day: 324 ===
Total batches (detected): 964
Batches with dynamic pickup (new batch arrived while previous had unfinished deliveries): 673 (69.81 %)

--- Per-courier Dynamic Pickup for Day: 324 ---

,delivery_user_id,total_batches_courier,dynamic_pickup_batches_courier,pct_dynamic_pickup
23,3d402c6f05639a1998cc32bbd40d3291,19,17,89.473684
80,e92bc5d64844655aa2ea7ddb3bb3ccd7,14,12,85.714286
1,02aa270595a0d24b1c9d2636fe249ebc,7,6,85.714286
42,6a76231746403d5448f6a5217034980d,20,17,85.000000
40,64f4e76e5f04dfbd0ffcf6b803a9f4f8,19,16,84.210526
8,0d6bd47d1eea4b6e553ba4fc18b332c7,18,15,83.333333
21,300db56eddc929594af6d741d231e0d3,18,15,83.333333
9,0d96b02a9ff59cef57bfad6df87161eb,18,15,83.333333
17,2eac82477425ea9e3b76985a3e8a1715,17,14,82.352941
32,58e622d6f803e740cc2f96d31f08ed1f,17,14,82.352941

... and 73 more couriers (showing top 10 by percentage).

    batch_size  count  sum  pct_dynamic
0            1    396  233    58.838384
1            2    223  174    78.026906
2            3    146  112    76.712329
3            4     88   67    76.136364
4            5     45   37    82.222222
5            6     31   25    80.645161
6            7     13    8    61.538462
7            8      7    5    71.428571
8            9      4    3    75.000000
9           10      1    1   100.000000
10          11      2    2   100.000000
11          12      3    3   100.000000
12          13      1    1   100.000000
13          14      2    1    50.000000
14          15      1    0     0.000000
15          16      1    1   100.000000

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-24 07:29:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
232,09536f632c9c0995d381907a98c0381a,2021-03-24 07:29:00,2021-03-24 08:13:00,0,0
233,8ede789d1939ad375514af6afebd05f4,2021-03-24 07:29:00,2021-03-24 08:43:00,1,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-24 07:30:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
234,53246663d716812e5121a466c6969881,2021-03-24 07:30:00,2021-03-24 08:33:00,0,1
235,b73c43bb55b00cf47b72a5606d623f2f,2021-03-24 07:30:00,2021-03-24 08:52:00,1,2
236,db20cc29e3748bf786c23bf12afedccb,2021-03-24 07:30:00,2021-03-24 08:23:00,2,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-24 07:32:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
237,5541c6848a3e07df3062e224a6f7ac1a,2021-03-24 07:32:00,2021-03-24 08:38:00,0,0
238,6f9aee8bbdd543d26f0c3a57d2f9bb52,2021-03-24 07:32:00,2021-03-24 09:07:00,1,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-24 07:33:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
239,7952d5149c2ae7ea81e0e1bbd6f29c14,2021-03-24 07:33:00,2021-03-24 09:24:00,0,1
240,c2f7fdafb6cec23465c9645d110f93af,2021-03-24 07:33:00,2021-03-24 09:16:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-24 09:43:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
242,aded9c9ac1568b9ee9fd7920bd24e9cd,2021-03-24 09:43:00,2021-03-24 10:19:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-24 09:44:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
243,6fe6426ee92b6793f9486747b1933e17,2021-03-24 09:44:00,2021-03-24 10:27:00,0,0
244,703c8da677114fadecb7873e848aab5a,2021-03-24 09:44:00,2021-03-24 10:45:00,1,1
245,d4d49591b7cdf86164476a8d6316abb9,2021-03-24 09:44:00,2021-03-24 11:31:00,2,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-24 09:45:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
246,46c711f5378d52fe128b8bc7f40cc9d9,2021-03-24 09:45:00,2021-03-24 10:55:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-24 12:39:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
248,0517241f422b2f525efeebe9e4795fac,2021-03-24 12:39:00,2021-03-24 14:19:00,0,1
249,102ec388e81c31ae0cac1631f2589283,2021-03-24 12:39:00,2021-03-24 13:24:00,1,0
250,85bad2a92bc6b2da5911169fee377cee,2021-03-24 12:39:00,2021-03-24 14:46:00,2,4
251,8e1e0d9ed4ea46324a363c18d9794886,2021-03-24 12:39:00,2021-03-24 14:39:00,3,3
252,dc8d9ed13163417fdb0ea80376dc348e,2021-03-24 12:39:00,2021-03-24 14:34:00,4,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-24 12:40:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
253,3b80510538a784a6e78f69185aeda5eb,2021-03-24 12:40:00,2021-03-24 14:10:00,0,1
254,88ada609498c173b1ba794aea5f84561,2021-03-24 12:40:00,2021-03-24 13:45:00,1,0
255,8d0c0a36e4dbc9bce0bb24223a4d9251,2021-03-24 12:40:00,2021-03-24 14:27:00,2,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-24 12:41:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
256,044867eef8dece3342606243bdaa5d55,2021-03-24 12:41:00,2021-03-24 13:40:00,0,1
257,1a191ea368337111a05bf74291569119,2021-03-24 12:41:00,2021-03-24 13:32:00,1,0
258,45bb9c6d991c2f6505d21b1093945720,2021-03-24 12:41:00,2021-03-24 13:58:00,2,2
259,7936578882203d13c69331486cbc9ad0,2021-03-24 12:41:00,2021-03-24 14:04:00,3,3

Saved batch summary to ./batch_dynamics_summary_shanghai_324.csv

=== Day: 325 ===
Total batches (detected): 979
Batches with dynamic pickup (new batch arrived while previous had unfinished deliveries): 680 (69.46 %)

--- Per-courier Dynamic Pickup for Day: 325 ---

,delivery_user_id,total_batches_courier,dynamic_pickup_batches_courier,pct_dynamic_pickup
9,156ba74f4cbb5799f74ba615fa586104,16,14,87.500000
71,d045adcdf9dccb37d9a87e91b54a9546,21,18,85.714286
18,2eac82477425ea9e3b76985a3e8a1715,20,17,85.000000
16,2bda9e538a98b75de75a2df2114c5f9b,20,17,85.000000
34,58e622d6f803e740cc2f96d31f08ed1f,19,16,84.210526
79,dbf1999be46b5dd2c1e475c3ca8d2de2,19,16,84.210526
44,6a76231746403d5448f6a5217034980d,19,16,84.210526
42,64f4e76e5f04dfbd0ffcf6b803a9f4f8,25,21,84.000000
6,0d6bd47d1eea4b6e553ba4fc18b332c7,18,15,83.333333
78,dafa5f217fe7f20dcb725a6af1339876,22,18,81.818182

... and 80 more couriers (showing top 10 by percentage).

    batch_size  count  sum  pct_dynamic
0            1    389  239    61.439589
1            2    245  180    73.469388
2            3    136  110    80.882353
3            4     89   58    65.168539
4            5     56   42    75.000000
5            6     21   18    85.714286
6            7     17   15    88.235294
7            8     13   10    76.923077
8            9      4    2    50.000000
9           10      1    1   100.000000
10          11      2    1    50.000000
11          12      3    1    33.333333
12          14      1    1   100.000000
13          17      1    1   100.000000
14          18      1    1   100.000000

Example courier: 02aa270595a0d24b1c9d2636fe249ebc receipt_time: 2021-03-25 10:25:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
682,152f0bf4e7163e07b1df52fa78bbe894,2021-03-25 10:25:00,2021-03-25 19:22:00,0,0
683,29c0644c5d7f0613d6d8f6b4e7854d24,2021-03-25 10:25:00,2021-03-28 21:27:00,1,3
684,795bb8a5cdaef6025861063baa9539f1,2021-03-25 10:25:00,2021-03-25 20:46:00,2,1
685,c7ffb4954ed0c4e94cc69592f1c07eb7,2021-03-25 10:25:00,2021-03-26 20:33:00,3,2

Example courier: 02aa270595a0d24b1c9d2636fe249ebc receipt_time: 2021-03-25 10:26:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
686,3868fce36007ee0f49b5b3f58240342e,2021-03-25 10:26:00,2021-03-25 20:27:00,0,1
687,c456085a5511a8828c9b0ebd92cfeff4,2021-03-25 10:26:00,2021-03-25 17:13:00,1,0

Example courier: 02aa270595a0d24b1c9d2636fe249ebc receipt_time: 2021-03-25 10:27:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
688,1257fa8cb2385ec04b73ebd9bc3c0f09,2021-03-25 10:27:00,2021-03-26 18:09:00,0,0

Example courier: 02ad3c5104d5605a3808ef675b94b253 receipt_time: 2021-03-25 07:46:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
983,1a317e6bcb486bc611c8860f27de24a8,2021-03-25 07:46:00,2021-03-25 09:11:00,0,2
984,4c34437d341d93136239a0622eeae9d5,2021-03-25 07:46:00,2021-03-25 08:59:00,1,0
985,66944ff50c7078d81c954da800068aeb,2021-03-25 07:46:00,2021-03-25 09:17:00,2,3
986,91e94d94c5a5e7124c4d1f65ebcdf52b,2021-03-25 07:46:00,2021-03-25 10:27:00,3,4
987,d4f4418d95fe1855c45461a3936f86ce,2021-03-25 07:46:00,2021-03-25 09:05:00,4,1

Example courier: 02ad3c5104d5605a3808ef675b94b253 receipt_time: 2021-03-25 07:47:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
988,13ba494468a1502a2a16066a265a6b32,2021-03-25 07:47:00,2021-03-25 08:52:00,0,1
989,5ff58237817bca7cd6fe8c04ccfc6b96,2021-03-25 07:47:00,2021-03-25 10:14:00,1,4
990,7ecda552c22bfed1375088bc2efe66b0,2021-03-25 07:47:00,2021-03-25 09:31:00,2,2
991,9dc4a298167ca018fcaa0111029f902d,2021-03-25 07:47:00,2021-03-25 09:43:00,3,3
992,a72ab0fa774e8cd588c27125e9a87bb3,2021-03-25 07:47:00,2021-03-25 08:20:00,4,0

Example courier: 02ad3c5104d5605a3808ef675b94b253 receipt_time: 2021-03-25 10:07:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
998,4cebef7c3f46ec793d7081412156acfa,2021-03-25 10:07:00,2021-03-25 11:22:00,0,4
999,57f16d42fabff6cc1e42df29f057858f,2021-03-25 10:07:00,2021-03-25 11:06:00,1,2
1000,7ee24e6dbba96dbd4f1a0ac76109fba3,2021-03-25 10:07:00,2021-03-25 10:51:00,2,1
1001,da925e9ed8ca2457eed53cf29e748207,2021-03-25 10:07:00,2021-03-25 11:11:00,3,3
1002,e6cae642f6b3a38d3ec0246efa7d7497,2021-03-25 10:07:00,2021-03-25 10:43:00,4,0

Example courier: 02ad3c5104d5605a3808ef675b94b253 receipt_time: 2021-03-25 12:14:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
1005,083f90a40ee9ca4dd43cbc2dbdec1c3f,2021-03-25 12:14:00,2021-03-25 13:27:00,0,6
1006,2a15297ad7f8c4966c535d505514b2a8,2021-03-25 12:14:00,2021-03-25 14:32:00,1,15
1007,3d3bc335b38d2b72b2cfb30daf32eac9,2021-03-25 12:14:00,2021-03-25 13:46:00,2,9
1008,4eaefb1ff757a33f3fde3253da02c33c,2021-03-25 12:14:00,2021-03-25 13:19:00,3,5
1009,50e8f3a1ed3d515cd7de17fffc139f24,2021-03-25 12:14:00,2021-03-25 13:32:00,4,7
1010,626d32ef5cde09dbc2283dc20d7f9eb0,2021-03-25 12:14:00,2021-03-25 13:51:00,5,10
1011,64ad0caaa311fd080f51e8db5c9b1c20,2021-03-25 12:14:00,2021-03-25 14:37:00,6,16
1012,6eba905415d8457100414fe6dba9b779,2021-03-25 12:14:00,2021-03-25 13:13:00,7,4
1013,72c713266c5f0ad735962dd92e613dd6,2021-03-25 12:14:00,2021-03-25 13:57:00,8,11
1014,746e4b07c803e2e2aeccd4a41e14f083,2021-03-25 12:14:00,2021-03-25 14:19:00,9,13
1015,773c50f3ddae5afa64909ce7ca20c467,2021-03-25 12:14:00,2021-03-25 14:24:00,10,14
1016,7f5980f1cdea44e06355cab02fc3799e,2021-03-25 12:14:00,2021-03-25 13:39:00,11,8
1017,88050caca02de5f3f03116ce88459073,2021-03-25 12:14:00,2021-03-25 13:00:00,12,2
1018,976f8f4b3fbf8e14fc0d1dd1dd66400f,2021-03-25 12:14:00,2021-03-25 14:05:00,13,12
1019,bedfffada024755759217235613bbc47,2021-03-25 12:14:00,2021-03-25 12:53:00,14,1
1020,c3b8ed360bff03f0808a9bf551e4f51e,2021-03-25 12:14:00,2021-03-25 14:45:00,15,17
1021,cf6acd632caa603ab6616b79055f7b95,2021-03-25 12:14:00,2021-03-25 12:44:00,16,0
1022,cfadebc5d443a8d0b78f2560b0f2ca23,2021-03-25 12:14:00,2021-03-25 13:06:00,17,3

Example courier: 02ad3c5104d5605a3808ef675b94b253 receipt_time: 2021-03-25 16:40:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
1024,27d09b3b77dca33de7d627a96ec8a2a1,2021-03-25 16:40:00,2021-03-25 17:55:00,0,2
1025,2d623105723edfc92ee33f59fddb7ffb,2021-03-25 16:40:00,2021-03-25 17:40:00,1,0
1026,433dd2ae2c0c320e296d1ecc4f44915c,2021-03-25 16:40:00,2021-03-25 18:03:00,2,3
1027,ad63c6902a793e388f1103fb1bfc1e9e,2021-03-25 16:40:00,2021-03-25 17:49:00,3,1
1028,e5175b164b304da1182e58ba9426279e,2021-03-25 16:40:00,2021-03-25 18:39:00,4,4

Example courier: 080c9121cdb81e512181bd93359acdb3 receipt_time: 2021-03-25 07:03:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
1938,931816fec88f540fb52d57802f8ee7d2,2021-03-25 07:03:00,2021-03-25 08:15:00,0,0

Example courier: 080c9121cdb81e512181bd93359acdb3 receipt_time: 2021-03-25 07:04:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
1939,3a1438e745a9b80fc74b681a9773307c,2021-03-25 07:04:00,2021-03-25 08:10:00,0,0

Saved batch summary to ./batch_dynamics_summary_shanghai_325.csv

=== Day: 326 ===
Total batches (detected): 1,002
Batches with dynamic pickup (new batch arrived while previous had unfinished deliveries): 702 (70.06 %)

--- Per-courier Dynamic Pickup for Day: 326 ---

,delivery_user_id,total_batches_courier,dynamic_pickup_batches_courier,pct_dynamic_pickup
10,156ba74f4cbb5799f74ba615fa586104,17,16,94.117647
68,ba13756ec3ac802658cf457f9bd12fde,11,10,90.909091
5,0b43ad0eea29bfd8e156f60e0f6b066e,20,18,90.000000
18,2eac82477425ea9e3b76985a3e8a1715,27,24,88.888889
38,58e622d6f803e740cc2f96d31f08ed1f,16,14,87.500000
48,6a76231746403d5448f6a5217034980d,23,20,86.956522
64,a953e787e74cc318462aa121e52d9896,21,18,85.714286
27,3d402c6f05639a1998cc32bbd40d3291,25,21,84.000000
83,dbf1999be46b5dd2c1e475c3ca8d2de2,17,14,82.352941
63,a8cdcf0689b7280ebd43c92a14444ed4,16,13,81.250000

... and 85 more couriers (showing top 10 by percentage).

    batch_size  count  sum  pct_dynamic
0            1    405  248    61.234568
1            2    243  182    74.897119
2            3    155  118    76.129032
3            4     81   66    81.481481
4            5     53   39    73.584906
5            6     29   21    72.413793
6            7     20   17    85.000000
7            8      3    2    66.666667
8            9      3    1    33.333333
9           10      7    5    71.428571
10          11      1    1   100.000000
11          12      2    2   100.000000

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-26 07:43:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
271,12c8dd5e544e530d542f4ab3418917a5,2021-03-26 07:43:00,2021-03-26 08:30:00,0,1
272,8135ee6598206edd916ba5b12fe81aa2,2021-03-26 07:43:00,2021-03-26 08:51:00,1,3
273,cd175bd076fe92741ffbd408a1952973,2021-03-26 07:43:00,2021-03-26 08:46:00,2,2
274,fcc0c944d4191822b481a50bd38deece,2021-03-26 07:43:00,2021-03-26 08:23:00,3,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-26 07:44:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
275,7d84c4360a296a0c932517caa10540e8,2021-03-26 07:44:00,2021-03-26 08:37:00,0,0
276,9d41971840b60b465bd1df98ab084763,2021-03-26 07:44:00,2021-03-26 09:08:00,1,2
277,f35ae7d3fc0aa502b727581a30527b15,2021-03-26 07:44:00,2021-03-26 08:57:00,2,1
278,fbe55760cc048cdb64286c0acade6bca,2021-03-26 07:44:00,2021-03-26 09:16:00,3,3

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-26 07:45:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
279,792f56bcc477415d9ce9bf0f6ff4c9d0,2021-03-26 07:45:00,2021-03-26 09:31:00,0,1
280,982947ee8f58f6ed478d1205bd85697c,2021-03-26 07:45:00,2021-03-26 09:38:00,1,2
281,c6c584e54d60592a450eb10770eddc32,2021-03-26 07:45:00,2021-03-26 09:50:00,2,3
282,ca13f07e653eac743d282187b7522ddf,2021-03-26 07:45:00,2021-03-26 09:24:00,3,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-26 07:46:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
283,b48e35829a79a42a488da964a0d7863a,2021-03-26 07:46:00,2021-03-26 10:20:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-26 11:27:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
285,4030c49fd53c49e5746f367b0c5ff599,2021-03-26 11:27:00,2021-03-26 13:34:00,0,0
286,c8156e6d08df41fabbf52ab7103e64f5,2021-03-26 11:27:00,2021-03-26 13:49:00,1,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-26 11:28:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
287,006953658354284ffb63b580a1aa8ff3,2021-03-26 11:28:00,2021-03-26 13:20:00,0,4
288,1e989f78b219bae221317a61d32f2e6e,2021-03-26 11:28:00,2021-03-26 12:20:00,1,0
289,49368f659f4009e3b48f26db604a5747,2021-03-26 11:28:00,2021-03-26 12:42:00,2,3
290,49bf31dfd812d0aa019a1f4f70c61caa,2021-03-26 11:28:00,2021-03-26 13:26:00,3,5
291,bcc0d20532cd5a9c24a96229f1c3673a,2021-03-26 11:28:00,2021-03-26 12:28:00,4,1
292,cfd586bd892bbe8761bb935acfd2f3ba,2021-03-26 11:28:00,2021-03-26 12:35:00,5,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-26 16:28:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
298,133a490efefc8f3409e955b020302ded,2021-03-26 16:28:00,2021-03-26 17:27:00,0,2
299,b50a6ab9c9cdb345b9065626a7d5a048,2021-03-26 16:28:00,2021-03-26 17:18:00,1,1
300,eeb3874e3fea3c8eeaf8551c48c53255,2021-03-26 16:28:00,2021-03-26 17:12:00,2,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-26 16:29:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
301,1a39a5c684edc988c0b629251b0e81dc,2021-03-26 16:29:00,2021-03-26 17:01:00,0,1
302,d4285e35fe390b49a48adcca043f8484,2021-03-26 16:29:00,2021-03-26 16:55:00,1,0

Example courier: 02aa270595a0d24b1c9d2636fe249ebc receipt_time: 2021-03-26 10:48:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
691,2246416b3b00a256e3d6ed488b3b2649,2021-03-26 10:48:00,2021-03-26 18:21:00,0,0
692,991afd3ed6e4679b25450a7d09929faf,2021-03-26 10:48:00,2021-03-28 20:53:00,1,1

Example courier: 02aa270595a0d24b1c9d2636fe249ebc receipt_time: 2021-03-26 10:49:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
693,096401cb1f6e1ecd85c148ad049c8d66,2021-03-26 10:49:00,2021-03-26 17:18:00,0,0
694,6b19efc5db3570ff13a3d1c3c347ccd7,2021-03-26 10:49:00,2021-03-27 17:26:00,1,3
695,acb792afe074867af2d5d72f66586565,2021-03-26 10:49:00,2021-03-26 17:24:00,2,1
696,c2c704eb6a2a7c8a921fa9eff7ff628a,2021-03-26 10:49:00,2021-03-26 20:16:00,3,2

Saved batch summary to ./batch_dynamics_summary_shanghai_326.csv

=== Day: 327 ===
Total batches (detected): 868
Batches with dynamic pickup (new batch arrived while previous had unfinished deliveries): 589 (67.86 %)

--- Per-courier Dynamic Pickup for Day: 327 ---

,delivery_user_id,total_batches_courier,dynamic_pickup_batches_courier,pct_dynamic_pickup
10,156ba74f4cbb5799f74ba615fa586104,16,15,93.750000
60,a2b97a310a6ac35c4480b26684f29aa7,11,10,90.909091
28,50cae56dcd1b73f4b4e5fdf3188c7fb2,7,6,85.714286
78,d3d20b5c70e919cad04f0484aade30cb,14,12,85.714286
88,f379666d8e2735e5b51ef8f9266d0bf9,7,6,85.714286
21,300db56eddc929594af6d741d231e0d3,21,18,85.714286
16,2eac82477425ea9e3b76985a3e8a1715,20,17,85.000000
63,a953e787e74cc318462aa121e52d9896,18,15,83.333333
54,9186a9f2138d421b852c1ad0abcc736b,17,14,82.352941
68,ba13756ec3ac802658cf457f9bd12fde,11,9,81.818182

... and 85 more couriers (showing top 10 by percentage).

    batch_size  count  sum  pct_dynamic
0            1    348  203    58.333333
1            2    186  139    74.731183
2            3    133  100    75.187970
3            4     83   65    78.313253
4            5     49   37    75.510204
5            6     29   21    72.413793
6            7     22   12    54.545455
7            8      4    2    50.000000
8            9      4    4   100.000000
9           10      5    2    40.000000
10          11      4    3    75.000000
11          13      1    1   100.000000

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-27 07:19:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
304,275384135f516acb0f6507146d60646b,2021-03-27 07:19:00,2021-03-27 09:18:00,0,1
305,883c1757de80e3b0f665f71dd035a391,2021-03-27 07:19:00,2021-03-27 10:07:00,1,2
306,ed599ab413f4798006963875a486ac51,2021-03-27 07:19:00,2021-03-27 08:15:00,2,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-27 07:20:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
307,2af476f84289653004a72ad2fc6c623b,2021-03-27 07:20:00,2021-03-27 10:53:00,0,4
308,6f157021e34b1f861779c08e3350efa1,2021-03-27 07:20:00,2021-03-27 08:47:00,1,2
309,8f5c4aa5787fc663fc2bcc0f9a7dd43c,2021-03-27 07:20:00,2021-03-27 10:36:00,2,3
310,918de6365ec546b575935c6e657a0bc7,2021-03-27 07:20:00,2021-03-27 08:42:00,3,1
311,ac419fb046095fbd45637daa69d1f5b0,2021-03-27 07:20:00,2021-03-27 08:36:00,4,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-27 07:21:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
312,40b9ea3446d216088bd8111c8f1a59dc,2021-03-27 07:21:00,2021-03-27 09:11:00,0,1
313,a2544cf0bfc71d9386c588ebc201a0ac,2021-03-27 07:21:00,2021-03-27 08:29:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-27 07:22:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
314,386ea04d8ac12c106c9b62fc890b10bf,2021-03-27 07:22:00,2021-03-27 08:22:00,0,0
315,915ebdf0438a563eb0e380663ccf948b,2021-03-27 07:22:00,2021-03-27 08:54:00,1,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-27 07:23:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
316,d831d192381449707dbadd6e8336c2a4,2021-03-27 07:23:00,2021-03-27 11:23:00,0,1
317,f5c2be8d217972d4a1239402314bc450,2021-03-27 07:23:00,2021-03-27 10:59:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-27 07:29:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
318,21d7e6bf9bfd3bd56807c0472d56eb63,2021-03-27 07:29:00,2021-03-27 09:01:00,0,0
319,473189d61c1b514ad7f8581b1326f5d4,2021-03-27 07:29:00,2021-03-27 10:01:00,1,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-27 07:30:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
320,13d51398ea35167cf12405e6a228fb4f,2021-03-27 07:30:00,2021-03-27 09:49:00,0,1
321,feb5edf40be9c543f3d39731ab654198,2021-03-27 07:30:00,2021-03-27 09:34:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-27 13:02:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
324,48c65a1dc31f159170f08d50cf10575f,2021-03-27 13:02:00,2021-03-27 14:39:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-27 13:03:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
325,764decac1b2fae56854b30c2fee10412,2021-03-27 13:03:00,2021-03-27 13:53:00,0,1
326,9275727f3847e5c7e4d9c83a171d66f9,2021-03-27 13:03:00,2021-03-27 14:15:00,1,3
327,99185d03ee73182434544885bde072ff,2021-03-27 13:03:00,2021-03-27 13:44:00,2,0
328,c745612cdb32db3c95f906831e84fc5e,2021-03-27 13:03:00,2021-03-27 14:51:00,3,4
329,d41ee016e2fc69feec96d31da3efafd9,2021-03-27 13:03:00,2021-03-27 13:59:00,4,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-27 13:04:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
330,1791385dd2e28a0285f57e4fff621432,2021-03-27 13:04:00,2021-03-27 14:24:00,0,1
331,67a5a62230d005dc92a3cf0b10f3a172,2021-03-27 13:04:00,2021-03-27 14:33:00,1,2
332,9a18551fc476692f2fc0c4f306fb0817,2021-03-27 13:04:00,2021-03-27 14:07:00,2,0
333,b7370d43d5f2fda0d438a951d254dd2e,2021-03-27 13:04:00,2021-03-27 15:02:00,3,4
334,cd3a736fa8ff6526fa0d51d57d5a9473,2021-03-27 13:04:00,2021-03-27 14:45:00,4,3

Saved batch summary to ./batch_dynamics_summary_shanghai_327.csv

=== Day: 328 ===
Total batches (detected): 941
Batches with dynamic pickup (new batch arrived while previous had unfinished deliveries): 650 (69.08 %)

--- Per-courier Dynamic Pickup for Day: 328 ---

,delivery_user_id,total_batches_courier,dynamic_pickup_batches_courier,pct_dynamic_pickup
13,2aa486c92101bb705e639db030ab0092,10,9,90.000000
9,156ba74f4cbb5799f74ba615fa586104,15,13,86.666667
21,300db56eddc929594af6d741d231e0d3,22,19,86.363636
64,a953e787e74cc318462aa121e52d9896,22,19,86.363636
16,2eac82477425ea9e3b76985a3e8a1715,18,15,83.333333
75,d1fda897c90233353f906db959a62b17,17,14,82.352941
60,a2b97a310a6ac35c4480b26684f29aa7,11,9,81.818182
53,8aa893234f416fc53f96fc43e0ff29b8,15,12,80.000000
82,dbf1999be46b5dd2c1e475c3ca8d2de2,15,12,80.000000
63,a8cdcf0689b7280ebd43c92a14444ed4,15,12,80.000000

... and 86 more couriers (showing top 10 by percentage).

    batch_size  count  sum  pct_dynamic
0            1    389  233    59.897172
1            2    201  154    76.616915
2            3    151  108    71.523179
3            4     83   70    84.337349
4            5     44   36    81.818182
5            6     37   24    64.864865
6            7     17   12    70.588235
7            8     12    9    75.000000
8            9      5    4    80.000000
9           12      1    0     0.000000
10          14      1    0     0.000000

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-28 07:47:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
355,24493bbd2568a834cb32dad1c410af6d,2021-03-28 07:47:00,2021-03-28 09:36:00,0,1
356,b5109349cf073fe0c5788b5f07e4754c,2021-03-28 07:47:00,2021-03-28 08:39:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-28 07:48:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
357,241780b00b43c87529f3e38f664b5d33,2021-03-28 07:48:00,2021-03-28 08:48:00,0,0
358,2ff7d274234fe8c45709d3ab0e487dcd,2021-03-28 07:48:00,2021-03-28 09:04:00,1,1
359,9dc999140e52c4a36dd70739739e34c4,2021-03-28 07:48:00,2021-03-28 10:25:00,2,4
360,a5f64ba9fe8ebd1950d8b40d210a4322,2021-03-28 07:48:00,2021-03-28 09:43:00,3,3
361,a77ca24a39d627c7af95b3b0eddac396,2021-03-28 07:48:00,2021-03-28 09:16:00,4,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-28 07:49:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
362,079b6ab3b55ce9b9ab40c1c9eb58badc,2021-03-28 07:49:00,2021-03-28 09:10:00,0,0
363,12ce246c26f3e29eb1d139ff060dfcd0,2021-03-28 07:49:00,2021-03-28 09:31:00,1,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-28 07:50:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
364,d18deb41e8e1c327e7eba107b3d02303,2021-03-28 07:50:00,2021-03-28 09:25:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-28 07:51:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
365,3b623c2cb4d17d44d223b9dd2817b5bd,2021-03-28 07:51:00,2021-03-28 10:20:00,0,2
366,5ae28722f8259dd634f36620f367ba38,2021-03-28 07:51:00,2021-03-28 10:03:00,1,0
367,f3228572b97ff79bce89b396c1fe13fa,2021-03-28 07:51:00,2021-03-28 10:09:00,2,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-28 07:52:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
368,7c099e5504b0d2399cf2b6d1fed703a4,2021-03-28 07:52:00,2021-03-28 09:54:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-28 13:25:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
371,09229564ae12b95e9d0781c5c98423cc,2021-03-28 13:25:00,2021-03-28 14:35:00,0,0
372,218d57fd211b0b6372a7a4ec44bf9df5,2021-03-28 13:25:00,2021-03-28 14:42:00,1,1
373,36310ab86ff91e64da1cb316867b5a5d,2021-03-28 13:25:00,2021-03-28 14:47:00,2,2
374,79098c9c306e88d4fdb67ce93e9f7d17,2021-03-28 13:25:00,2021-03-28 15:04:00,3,3

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-28 13:26:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
375,bf66d6eea1a317c3186c9213485dd246,2021-03-28 13:26:00,2021-03-28 14:21:00,0,1
376,dc4af3d2a06434ad876c4d194c9f501b,2021-03-28 13:26:00,2021-03-28 14:27:00,1,2
377,ed1a672f898f6c1c5b33d2e2bcc0338b,2021-03-28 13:26:00,2021-03-28 14:16:00,2,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-28 16:53:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
381,40fce7970fe776aac2717bcdce4563fe,2021-03-28 16:53:00,2021-03-28 17:44:00,0,0
382,6d8abce5ace50dd3f7ae6fcfc5e2e8b5,2021-03-28 16:53:00,2021-03-28 19:59:00,1,2
383,c37b791c7918ab03085fe340f7a695b8,2021-03-28 16:53:00,2021-03-28 20:22:00,2,4
384,c3a03c22ea074dc487e9e08a23177910,2021-03-28 16:53:00,2021-03-28 17:51:00,3,1
385,c6bf752be52eaa6d7605c48f4ec411fc,2021-03-28 16:53:00,2021-03-28 20:05:00,4,3
386,e4ac8831e29bdf13f04cd283c8658d03,2021-03-28 16:53:00,2021-03-28 20:27:00,5,5

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-28 17:16:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
387,06af03d41f0eb70bb2dc2c6ae633b157,2021-03-28 17:16:00,2021-03-28 18:06:00,0,0
388,136db156ff6ae4c7994c46472b889289,2021-03-28 17:16:00,2021-03-28 19:18:00,1,5
389,3abc24be95b57056cfeb89b04ea0f6c5,2021-03-28 17:16:00,2021-03-28 19:49:00,2,6
390,89e67990d8c551cfce3481cedd092340,2021-03-28 17:16:00,2021-03-28 18:27:00,3,2
391,bbcda4a4a2ed1877975827ae71fff0be,2021-03-28 17:16:00,2021-03-28 18:16:00,4,1
392,d5369fc36854a1dcabe3d1b1715d8272,2021-03-28 17:16:00,2021-03-28 19:13:00,5,4
393,e78be10e438a8bdd604ae0b5344f47bf,2021-03-28 17:16:00,2021-03-28 18:35:00,6,3

Saved batch summary to ./batch_dynamics_summary_shanghai_328.csv

=== Day: 329 ===
Total batches (detected): 846
Batches with dynamic pickup (new batch arrived while previous had unfinished deliveries): 589 (69.62 %)

--- Per-courier Dynamic Pickup for Day: 329 ---

,delivery_user_id,total_batches_courier,dynamic_pickup_batches_courier,pct_dynamic_pickup
52,956fa147a5956d928b8c9734a98828cf,12,11,91.666667
17,2eac82477425ea9e3b76985a3e8a1715,27,24,88.888889
7,0d96b02a9ff59cef57bfad6df87161eb,25,22,88.000000
82,faa55abcf03dce5c565a139c2c31e84f,8,7,87.500000
56,a8cdcf0689b7280ebd43c92a14444ed4,14,12,85.714286
54,a2b97a310a6ac35c4480b26684f29aa7,14,12,85.714286
14,2aa486c92101bb705e639db030ab0092,7,6,85.714286
34,58e622d6f803e740cc2f96d31f08ed1f,13,11,84.615385
22,300db56eddc929594af6d741d231e0d3,18,15,83.333333
1,02aa270595a0d24b1c9d2636fe249ebc,6,5,83.333333

... and 77 more couriers (showing top 10 by percentage).

   batch_size  count  sum  pct_dynamic
0           1    359  236    65.738162
1           2    176  136    77.272727
2           3    144  107    74.305556
3           4     76   49    64.473684
4           5     40   30    75.000000
5           6     19   14    73.684211
6           7     15    8    53.333333
7           8      9    5    55.555556
8           9      5    2    40.000000
9          10      3    2    66.666667

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-29 07:41:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
399,4de42b927cccad8563df25a90bf4b004,2021-03-29 07:41:00,2021-03-29 08:26:00,0,1
400,6916bf3910e4ebd8770d0998a127c4a8,2021-03-29 07:41:00,2021-03-29 08:54:00,1,4
401,9cb1b87c71cafde846fb7d9537fc1280,2021-03-29 07:41:00,2021-03-29 08:38:00,2,3
402,ae935655972556c1b57a4f8b450d9376,2021-03-29 07:41:00,2021-03-29 08:21:00,3,0
403,b60db02946469faab4713b2a12ae04e1,2021-03-29 07:41:00,2021-03-29 09:04:00,4,5
404,f304b59f2bd361acbeafc5735bceaa51,2021-03-29 07:41:00,2021-03-29 08:33:00,5,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-29 07:42:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
405,4c7aefefa1fa50fd566622d73445716e,2021-03-29 07:42:00,2021-03-29 09:25:00,0,1
406,a46765f18aaa9bef70ef2963963cb996,2021-03-29 07:42:00,2021-03-29 08:45:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-29 07:43:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
407,63daecba988c21d68273f959f74dd520,2021-03-29 07:43:00,2021-03-29 09:48:00,0,3
408,784d790a9d30c2556612f72e1a3b2ac0,2021-03-29 07:43:00,2021-03-29 09:36:00,1,1
409,87d09a3c3fb68a396b5ac56d59dafb9e,2021-03-29 07:43:00,2021-03-29 09:20:00,2,0
410,a5221f7e0a19a83bd3f27899f7aa581f,2021-03-29 07:43:00,2021-03-29 09:42:00,3,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-29 07:44:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
411,839b7c53a8610158e6345fdf2333881e,2021-03-29 07:44:00,2021-03-29 09:53:00,0,1
412,8878b9ed8f99525307cec37353d71733,2021-03-29 07:44:00,2021-03-29 09:30:00,1,0
413,931c94db869064090653bf3c8206f323,2021-03-29 07:44:00,2021-03-29 11:11:00,2,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-29 07:45:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
414,0c0834022f6550b19b7581c5aa589e77,2021-03-29 07:45:00,2021-03-29 11:17:00,0,2
415,260124ece1b365f60cf200423dec2669,2021-03-29 07:45:00,2021-03-29 11:05:00,1,1
416,b45ce1d06417bd987e4f313f3dbf0645,2021-03-29 07:45:00,2021-03-29 10:57:00,2,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-29 13:27:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
418,6153dff600181b11db3c763f8ee3342c,2021-03-29 13:27:00,2021-03-29 15:44:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-29 13:28:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
419,550a59f661b170d1872484e7ee26f7f6,2021-03-29 13:28:00,2021-03-29 15:31:00,0,2
420,c8f33c7370a83f9650c07433bff17625,2021-03-29 13:28:00,2021-03-29 15:16:00,1,1
421,fdeccbe6ed4f998078bc3e72f834355a,2021-03-29 13:28:00,2021-03-29 14:22:00,2,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-29 13:29:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
422,1845e6e033b172b1291057df0205e122,2021-03-29 13:29:00,2021-03-29 14:13:00,0,1
423,5cde3a268806cb99e6d1d12254c3b0eb,2021-03-29 13:29:00,2021-03-29 14:07:00,1,0
424,67c167cd69c3e248c3d26631a3ea5a24,2021-03-29 13:29:00,2021-03-29 15:10:00,2,2
425,70940cd230913909a01216a281d80784,2021-03-29 13:29:00,2021-03-29 15:23:00,3,3

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-29 13:30:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
426,be66b5f3c8bc3bad5bf4268088b9c268,2021-03-29 13:30:00,2021-03-29 14:37:00,0,0
427,e0323fad896366af3abd978aa3ff5396,2021-03-29 13:30:00,2021-03-29 14:47:00,1,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-29 16:37:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
429,84933039d4582f7df66471dccf50a3db,2021-03-29 16:37:00,2021-03-29 18:04:00,0,2
430,ad29d00bd3e8b233e12dfd798dacc78d,2021-03-29 16:37:00,2021-03-29 17:47:00,1,1
431,e82af6969ac86a5c65d2cd1712aef6ea,2021-03-29 16:37:00,2021-03-29 17:37:00,2,0

Saved batch summary to ./batch_dynamics_summary_shanghai_329.csv

=== Day: 330 ===
Total batches (detected): 851
Batches with dynamic pickup (new batch arrived while previous had unfinished deliveries): 593 (69.68 %)

--- Per-courier Dynamic Pickup for Day: 330 ---

,delivery_user_id,total_batches_courier,dynamic_pickup_batches_courier,pct_dynamic_pickup
34,58e622d6f803e740cc2f96d31f08ed1f,17,15,88.235294
17,2eac82477425ea9e3b76985a3e8a1715,24,21,87.500000
22,300db56eddc929594af6d741d231e0d3,20,17,85.000000
46,6a76231746403d5448f6a5217034980d,19,16,84.210526
8,0d96b02a9ff59cef57bfad6df87161eb,25,21,84.000000
58,956fa147a5956d928b8c9734a98828cf,25,21,84.000000
1,02aa270595a0d24b1c9d2636fe249ebc,6,5,83.333333
78,e58a1784fb1aab32a3f38f300dc8e14b,6,5,83.333333
5,0b43ad0eea29bfd8e156f60e0f6b066e,17,14,82.352941
57,9338334d1ca57094ab3703f0eea8efa0,22,18,81.818182

... and 75 more couriers (showing top 10 by percentage).

    batch_size  count  sum  pct_dynamic
0            1    355  224    63.098592
1            2    193  141    73.056995
2            3    115   91    79.130435
3            4     93   69    74.193548
4            5     42   27    64.285714
5            6     19   16    84.210526
6            7     10    8    80.000000
7            8     10    8    80.000000
8            9      6    4    66.666667
9           10      3    2    66.666667
10          11      1    1   100.000000
11          12      1    1   100.000000
12          13      3    1    33.333333

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-30 07:30:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
435,1fa702196ac262f8ace5c1eeb1ec093c,2021-03-30 07:30:00,2021-03-30 08:25:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-30 07:31:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
436,18b223e9ee98bc9b430001eefd6ac4c6,2021-03-30 07:31:00,2021-03-30 11:55:00,0,2
437,549e9444616f558d42922323d131aff6,2021-03-30 07:31:00,2021-03-30 08:31:00,1,1
438,bf87b2019bcba772f677f3b5a2e0eaf3,2021-03-30 07:31:00,2021-03-30 08:20:00,2,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-30 07:32:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
439,0f291ba029a05a9eb9c1a6c69b4c2f69,2021-03-30 07:32:00,2021-03-30 09:14:00,0,3
440,2efdb09c60d97092e4f3c04c38c75604,2021-03-30 07:32:00,2021-03-30 09:04:00,1,2
441,7516a4695679e53664159c07cf9b011f,2021-03-30 07:32:00,2021-03-30 08:39:00,2,0
442,e43cbf290535a612d7660132e74098ea,2021-03-30 07:32:00,2021-03-30 08:58:00,3,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-30 07:33:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
443,dd231715b8a6d02e0c92e3140c39f1df,2021-03-30 07:33:00,2021-03-30 08:49:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-30 07:34:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
444,1c211f5ff981406d494927de5232f6e5,2021-03-30 07:34:00,2021-03-30 09:49:00,0,1
445,4174cabc3a8185b96e85ef53823a0049,2021-03-30 07:34:00,2021-03-30 10:09:00,1,2
446,6cabbf491b8f702b085535f0912fbea1,2021-03-30 07:34:00,2021-03-30 09:23:00,2,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-30 07:35:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
447,4252b5b204e722b7f4bf2685d5f36229,2021-03-30 07:35:00,2021-03-30 09:42:00,0,1
448,639f7f10242896b0e4da6af064e90fc6,2021-03-30 07:35:00,2021-03-30 10:00:00,1,3
449,6926cfaa7ad1511a4f418d2e3871b534,2021-03-30 07:35:00,2021-03-30 09:34:00,2,0
450,b18189334adaceb76ffbbdee95e6a9ed,2021-03-30 07:35:00,2021-03-30 09:55:00,3,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-30 13:46:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
455,4fee8db544b797d992d4afe29655c767,2021-03-30 13:46:00,2021-03-30 15:22:00,0,4
456,7608b338ea5ee1063061e67b37d27863,2021-03-30 13:46:00,2021-03-30 14:41:00,1,2
457,de9134cfd0eb3138243385b03fd8b453,2021-03-30 13:46:00,2021-03-30 14:31:00,2,1
458,eba42bf3fcda6ce23b27d27e6ba33984,2021-03-30 13:46:00,2021-03-30 14:19:00,3,0
459,ebd95bcb4fa89d03252ce55c9a3bc2d9,2021-03-30 13:46:00,2021-03-30 14:55:00,4,3

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-30 13:47:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
460,6bacf78e4c422cc6091e58e712ced6d0,2021-03-30 13:47:00,2021-03-30 14:49:00,0,1
461,80f8303c809fb1aac20b887d52de28af,2021-03-30 13:47:00,2021-03-30 14:25:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-30 17:27:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
463,4ab5ac5bc8e43a392a899086c57aba8a,2021-03-30 17:27:00,2021-03-30 17:58:00,0,0
464,64f7e0e892288afe4337f666c1386444,2021-03-30 17:27:00,2021-03-30 18:09:00,1,1
465,8380f3593a5043fa7399ed6b216922fb,2021-03-30 17:27:00,2021-03-30 18:41:00,2,4
466,d8e23a892f700a36ce6922207a9cd936,2021-03-30 17:27:00,2021-03-30 18:36:00,3,3
467,f57a18b4111af2b3fe4b7094d3ab16c1,2021-03-30 17:27:00,2021-03-30 18:17:00,4,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-30 17:28:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
468,349a09b3113442a94c53a6a61cef4ae5,2021-03-30 17:28:00,2021-03-30 19:05:00,0,2
469,7753c11493925854724df6f64f2b3ef7,2021-03-30 17:28:00,2021-03-30 18:24:00,1,1
470,ff8eb62f452698112eacc8740603266d,2021-03-30 17:28:00,2021-03-30 18:03:00,2,0

Saved batch summary to ./batch_dynamics_summary_shanghai_330.csv

=== Day: 331 ===
Total batches (detected): 942
Batches with dynamic pickup (new batch arrived while previous had unfinished deliveries): 688 (73.04 %)

--- Per-courier Dynamic Pickup for Day: 331 ---

,delivery_user_id,total_batches_courier,dynamic_pickup_batches_courier,pct_dynamic_pickup
32,58e622d6f803e740cc2f96d31f08ed1f,22,20,90.909091
17,2eac82477425ea9e3b76985a3e8a1715,24,21,87.500000
66,d33195a6861ad4ef40a499d75c74c8ee,16,14,87.500000
1,02aa270595a0d24b1c9d2636fe249ebc,8,7,87.500000
5,0b43ad0eea29bfd8e156f60e0f6b066e,30,26,86.666667
8,0d96b02a9ff59cef57bfad6df87161eb,21,18,85.714286
38,64f4e76e5f04dfbd0ffcf6b803a9f4f8,20,17,85.000000
10,156ba74f4cbb5799f74ba615fa586104,13,11,84.615385
48,8a73fcab52b71786d4c3a2e0e12cdcdc,26,22,84.615385
4,080c9121cdb81e512181bd93359acdb3,6,5,83.333333

... and 71 more couriers (showing top 10 by percentage).

    batch_size  count  sum  pct_dynamic
0            1    338  223    65.976331
1            2    244  189    77.459016
2            3    140  116    82.857143
3            4     83   68    81.927711
4            5     67   46    68.656716
5            6     25   19    76.000000
6            7     19    9    47.368421
7            8      9    7    77.777778
8            9      8    4    50.000000
9           10      4    4   100.000000
10          11      4    3    75.000000
11          15      1    0     0.000000

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-31 07:33:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
472,1df15fcce17a2dfb356c68b214ffc61c,2021-03-31 07:33:00,2021-03-31 08:31:00,0,0
473,391cd18987073bf6a1cbdebed75d2196,2021-03-31 07:33:00,2021-03-31 08:50:00,1,1
474,dc39327b939f3fe9e3df37c8ffe65f92,2021-03-31 07:33:00,2021-03-31 08:56:00,2,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-31 07:34:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
475,0c9e0c08814f97b459577b1b9c7e676c,2021-03-31 07:34:00,2021-03-31 08:37:00,0,0
476,113895d3a2abc3256affa0dd65863996,2021-03-31 07:34:00,2021-03-31 09:04:00,1,1
477,26e17e700e968976c0fa7a67cccb63b0,2021-03-31 07:34:00,2021-03-31 09:21:00,2,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-31 07:35:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
478,1a83f153d9c216bea948b16041097422,2021-03-31 07:35:00,2021-03-31 10:14:00,0,6
479,5c1c8270217902675a8eb2dc59851ca6,2021-03-31 07:35:00,2021-03-31 09:15:00,1,0
480,6134932eb40bfdeaeaabbd8ba43d83d3,2021-03-31 07:35:00,2021-03-31 09:27:00,2,1
481,81955f5df937712bcc4d6129cb6338e0,2021-03-31 07:35:00,2021-03-31 10:05:00,3,5
482,af89b9c4c31de3ef20dd0f1efff7849f,2021-03-31 07:35:00,2021-03-31 09:32:00,4,2
483,dd29d1fb196e544c719aa7f60cbaed68,2021-03-31 07:35:00,2021-03-31 09:44:00,5,3
484,ec451f9bdf60f77091b21528664161f0,2021-03-31 07:35:00,2021-03-31 09:52:00,6,4

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-31 07:36:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
485,f377353c31d9188cc8d8b9836c7490b3,2021-03-31 07:36:00,2021-03-31 10:35:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-31 07:37:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
486,32e0a99785955a5db1e6045304e79a1e,2021-03-31 07:37:00,2021-03-31 10:23:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-31 12:22:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
488,8f1798d16d74a98e165e95be1ead3684,2021-03-31 12:22:00,2021-03-31 14:40:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-31 12:23:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
489,515542f9373eb851ff0586bfba60fe40,2021-03-31 12:23:00,2021-03-31 14:28:00,0,0
490,642bbbb67cb89666102df73866f4ca2d,2021-03-31 12:23:00,2021-03-31 16:15:00,1,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-31 12:24:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
491,2b3c390e68c7845a9452d257b9a2872a,2021-03-31 12:24:00,2021-03-31 18:26:00,0,3
492,c2752488cecca04959929d82b0eed81f,2021-03-31 12:24:00,2021-03-31 17:36:00,1,1
493,c287869b85dc535f9b85ccfb8a2d68a3,2021-03-31 12:24:00,2021-03-31 16:08:00,2,0
494,e0513a92cd3fe66f46367979905221e0,2021-03-31 12:24:00,2021-03-31 18:20:00,3,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-31 12:26:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
495,985f4d6a206d8d0c5b7d7a8d442e3b4a,2021-03-31 12:26:00,2021-03-31 17:46:00,0,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-03-31 12:28:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
496,fcffcb7dd803e8bca2c111374ea358a5,2021-03-31 12:28:00,2021-03-31 18:15:00,0,0

Saved batch summary to ./batch_dynamics_summary_shanghai_331.csv

=== Day: 401 ===
Total batches (detected): 981
Batches with dynamic pickup (new batch arrived while previous had unfinished deliveries): 715 (72.88 %)

--- Per-courier Dynamic Pickup for Day: 401 ---

,delivery_user_id,total_batches_courier,dynamic_pickup_batches_courier,pct_dynamic_pickup
1,02aa270595a0d24b1c9d2636fe249ebc,9,8,88.888889
16,2cd6a9a317e3cc0dc8aae36443f5d806,18,16,88.888889
5,0b43ad0eea29bfd8e156f60e0f6b066e,30,26,86.666667
51,a953e787e74cc318462aa121e52d9896,21,18,85.714286
36,6a76231746403d5448f6a5217034980d,20,17,85.000000
9,156ba74f4cbb5799f74ba615fa586104,13,11,84.615385
17,2eac82477425ea9e3b76985a3e8a1715,19,16,84.210526
70,eda32f67c0f4789e8956cd30552df302,6,5,83.333333
34,64f4e76e5f04dfbd0ffcf6b803a9f4f8,24,20,83.333333
14,2aa486c92101bb705e639db030ab0092,6,5,83.333333

... and 67 more couriers (showing top 10 by percentage).

    batch_size  count  sum  pct_dynamic
0            1    407  266    65.356265
1            2    213  165    77.464789
2            3    167  133    79.640719
3            4     81   65    80.246914
4            5     51   40    78.431373
5            6     26   22    84.615385
6            7     15    9    60.000000
7            8      5    4    80.000000
8            9      6    4    66.666667
9           10      4    2    50.000000
10          11      3    2    66.666667
11          12      2    2   100.000000
12          15      1    1   100.000000

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-04-01 07:34:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
509,07ce7054ddbd93a78df67c4ca8dfdbc5,2021-04-01 07:34:00,2021-04-01 10:00:00,0,1
510,0a8069c354085c0fe74cfdf6142a028c,2021-04-01 07:34:00,2021-04-01 09:51:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-04-01 07:35:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
511,537591252fcb0ac3af8632b2c3447af4,2021-04-01 07:35:00,2021-04-01 10:09:00,0,1
512,ef54abfff5aaaf697be200b5ca858015,2021-04-01 07:35:00,2021-04-01 09:43:00,1,0
513,fbd08cb063b6d930556a884628606b86,2021-04-01 07:35:00,2021-04-01 10:36:00,2,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-04-01 07:36:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
514,04f27eca64ed4aa0cfd108520e29fc00,2021-04-01 07:36:00,2021-04-01 11:08:00,0,5
515,20b86d7ea7eae87e4dfa798350261972,2021-04-01 07:36:00,2021-04-01 11:15:00,1,6
516,624105faa5141dbacca4eb306a544934,2021-04-01 07:36:00,2021-04-01 09:00:00,2,0
517,761cd619aa63bba0fee89c08ac427e01,2021-04-01 07:36:00,2021-04-01 10:23:00,3,3
518,cad30d9b9f19b62bad458ca382267332,2021-04-01 07:36:00,2021-04-01 09:14:00,4,2
519,d037cfff2e81ba0542d0bac538786226,2021-04-01 07:36:00,2021-04-01 10:59:00,5,4
520,d7dc72b4c0a1cb7d7a78d8646d3208a2,2021-04-01 07:36:00,2021-04-01 09:06:00,6,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-04-01 07:37:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
521,0c7cd7e41b073d4f2bbcf8b2e5b37ec8,2021-04-01 07:37:00,2021-04-01 09:30:00,0,2
522,683bb879946a61af360ca5b15644d4b1,2021-04-01 07:37:00,2021-04-01 09:21:00,1,1
523,91408b62b204a718b21f64eec6220d08,2021-04-01 07:37:00,2021-04-01 10:50:00,2,4
524,b3b51bee2aa408fc2c3573b0d71c0876,2021-04-01 07:37:00,2021-04-01 08:31:00,3,0
525,d7845dcca4868adf1fab40cb24759f2a,2021-04-01 07:37:00,2021-04-01 09:36:00,4,3

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-04-01 12:22:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
529,6ba1282ceb33058818ed44a7334e2c74,2021-04-01 12:22:00,2021-04-01 13:29:00,0,0
530,775aae53068472987d99766d00c19c02,2021-04-01 12:22:00,2021-04-01 13:51:00,1,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-04-01 12:23:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
531,5c1eb3b62c7b0396c87630fbbc415977,2021-04-01 12:23:00,2021-04-01 14:00:00,0,0
532,d8a98cd384c3cad5bd1f87d0980fd6ac,2021-04-01 12:23:00,2021-04-01 14:52:00,1,2
533,ede25d91ac9a026f116ed5ec484aba57,2021-04-01 12:23:00,2021-04-01 14:06:00,2,1

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-04-01 12:24:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
534,25224a9c7f12c65da803727b1b563c62,2021-04-01 12:24:00,2021-04-01 13:36:00,0,1
535,b7bfdadb14fd46c3271e3bc31ad903c2,2021-04-01 12:24:00,2021-04-01 13:22:00,1,0
536,c7b57bb28f72f1d6ba5589637a0adc83,2021-04-01 12:24:00,2021-04-01 14:16:00,2,2

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-04-01 12:25:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
537,770fcf81efa36caf967de4d88c4eaa83,2021-04-01 12:25:00,2021-04-01 13:43:00,0,1
538,de5f09e42f8fde8f2fdd8ebf47dd3a94,2021-04-01 12:25:00,2021-04-01 13:15:00,1,0

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-04-01 16:26:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
540,70f84e4e86921598e7497ff6e2780fa0,2021-04-01 16:26:00,2021-04-01 19:47:00,0,5
541,8d6246c6050cb1d77392c47654f1e99c,2021-04-01 16:26:00,2021-04-01 18:32:00,1,0
542,b3feb62599df7b3f59071f9a8c339c71,2021-04-01 16:26:00,2021-04-01 18:43:00,2,1
543,bfacb5e8673ff52bb1bc3de16cdf1cfa,2021-04-01 16:26:00,2021-04-01 19:08:00,3,4
544,e4f07c20bfc03a3b79852780481cd84b,2021-04-01 16:26:00,2021-04-01 18:50:00,4,2
545,ffba1566b3eb44f0b809f84c78664e6e,2021-04-01 16:26:00,2021-04-01 19:02:00,5,3

Example courier: 00fca617ad52d2deb9650342901a1940 receipt_time: 2021-04-01 16:27:00

,order_id,receipt_time,sign_time,batch_rank_dispatch,batch_rank_actual
546,e81549607af585412ae0282285d91096,2021-04-01 16:27:00,2021-04-01 20:00:00,0,0

Saved batch summary to ./batch_dynamics_summary_shanghai_401.csv

In [ ]:
# Optional: save batch-level summary for further analysis
OUT = './batch_dynamics_summary_' + CITY.lower() + '.csv'
batches.to_csv(OUT, index=False)
print('Saved batch summary to', OUT)

## Notes
- This notebook treats orders with identical `receipt_time` (same courier) as part of the same batch, matching the LaDe pipeline's definition.
- Dynamic pickup is detected when a later batch's `receipt_time` occurs while some orders in the earlier batch remain unsigned (`sign_time > next_batch_receipt_time`).
- If `sign_time` is missing or inaccurate, consider using courier GPS traces or delivery status logs to refine the overlap definition.

If you want, I can run this notebook for a specific city file in your environment, or extend it to visualise temporal overlap per courier.